// Code generated by hertz generator.

package metrics

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/common/config"
	"github.com/cloudwego/hertz/pkg/protocol"
	v1 "monitor_hub/apis/pushgateway/metrics/v1"
	v10 "monitor_hub/apis/monitor_hub/base/v1"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type Client interface {
	ReportMetrics(context context.Context, req *v1.ReportMetricsRequest, reqOpt ...config.RequestOption) (resp *v1.ReportMetricResponse, rawResponse *protocol.Response, err error)

	QueryMetrics(context context.Context, req *v1.MetricQuery, reqOpt ...config.RequestOption) (resp *v10.Response, rawResponse *protocol.Response, err error)

	GetStats(context context.Context, req *v1.GetStatsRequest, reqOpt ...config.RequestOption) (resp *v10.Response, rawResponse *protocol.Response, err error)
}

type MetricsServiceClient struct {
	client *cli
}

func NewMetricsServiceClient(hostUrl string, ops ...Option) (Client, error) {
	opts := getOptions(append(ops, withHostUrl(hostUrl))...)
	cli, err := newClient(opts)
	if err != nil {
		return nil, err
	}
	return &MetricsServiceClient{
		client: cli,
	}, nil
}

func (s *MetricsServiceClient) ReportMetrics(context context.Context, req *v1.ReportMetricsRequest, reqOpt ...config.RequestOption) (resp *v1.ReportMetricResponse, rawResponse *protocol.Response, err error) {
	httpResp := &v1.ReportMetricResponse{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{}).
		setPathParams(map[string]string{}).
		addHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("POST", "/apis/v1/metrics/batch")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

func (s *MetricsServiceClient) QueryMetrics(context context.Context, req *v1.MetricQuery, reqOpt ...config.RequestOption) (resp *v10.Response, rawResponse *protocol.Response, err error) {
	httpResp := &v10.Response{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{}).
		setPathParams(map[string]string{}).
		addHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("POST", "/apis/v1/metrics/query")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

func (s *MetricsServiceClient) GetStats(context context.Context, req *v1.GetStatsRequest, reqOpt ...config.RequestOption) (resp *v10.Response, rawResponse *protocol.Response, err error) {
	httpResp := &v10.Response{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{}).
		setPathParams(map[string]string{}).
		addHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("POST", "/apis/v1/metrics/query_stats")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

var defaultClient, _ = NewMetricsServiceClient("")

func ConfigDefaultClient(ops ...Option) (err error) {
	defaultClient, err = NewMetricsServiceClient("", ops...)
	return
}

func ReportMetrics(context context.Context, req *v1.ReportMetricsRequest, reqOpt ...config.RequestOption) (resp *v1.ReportMetricResponse, rawResponse *protocol.Response, err error) {
	return defaultClient.ReportMetrics(context, req, reqOpt...)
}

func QueryMetrics(context context.Context, req *v1.MetricQuery, reqOpt ...config.RequestOption) (resp *v10.Response, rawResponse *protocol.Response, err error) {
	return defaultClient.QueryMetrics(context, req, reqOpt...)
}

func GetStats(context context.Context, req *v1.GetStatsRequest, reqOpt ...config.RequestOption) (resp *v10.Response, rawResponse *protocol.Response, err error) {
	return defaultClient.GetStats(context, req, reqOpt...)
}
