// Code generated by hzx generator. you can insert middleware here.
package v1

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}
func _createmarkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _batchcreatemarkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listmarkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setmarkexpiredMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apisMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _markMw() []app.HandlerFunc {
	// your code...
	return nil
}


