// Generated by gve api generate. Do not edit manually.

import type { CreateStoreConfigRequest, CreateStoreConfigResponse, DeleteStoreConfigRequest, GetStoreConfigRequest, GetStoreConfigResponse, ListStoreConfigsRequest, ListStoreConfigsResponse, UpdateStoreConfigRequest } from "./types";

/** Options for customizing client behavior. */
interface ClientOptions {
  fetch?: typeof globalThis.fetch;
  baseHeaders?: Record<string, string>;
  onError?: (error: Error, method: string) => void;
}

export class StoreConfigServiceClient {
  private readonly baseUrl: string;
  private readonly options: ClientOptions;

  constructor(baseUrl: string, options?: ClientOptions) {
    this.baseUrl = baseUrl;
    this.options = options ?? {};
  }

  async CreateStoreConfig(reqBody: CreateStoreConfigRequest): Promise<CreateStoreConfigResponse> {
    const fetchFn = this.options.fetch ?? globalThis.fetch;
    const response = await fetchFn(`${this.baseUrl}/CreateStoreConfig`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...this.options.baseHeaders,
      },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      const error = new Error(`request failed: status=${response.status}, body=${text}`);
      this.options.onError?.(error, "CreateStoreConfig");
      throw error;
    }

    return (await response.json()) as CreateStoreConfigResponse;
  }

  async GetStoreConfig(reqBody: GetStoreConfigRequest): Promise<GetStoreConfigResponse> {
    const fetchFn = this.options.fetch ?? globalThis.fetch;
    const response = await fetchFn(`${this.baseUrl}/GetStoreConfig`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...this.options.baseHeaders,
      },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      const error = new Error(`request failed: status=${response.status}, body=${text}`);
      this.options.onError?.(error, "GetStoreConfig");
      throw error;
    }

    return (await response.json()) as GetStoreConfigResponse;
  }

  async ListStoreConfigs(reqBody: ListStoreConfigsRequest): Promise<ListStoreConfigsResponse> {
    const fetchFn = this.options.fetch ?? globalThis.fetch;
    const response = await fetchFn(`${this.baseUrl}/ListStoreConfigs`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...this.options.baseHeaders,
      },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      const error = new Error(`request failed: status=${response.status}, body=${text}`);
      this.options.onError?.(error, "ListStoreConfigs");
      throw error;
    }

    return (await response.json()) as ListStoreConfigsResponse;
  }

  async UpdateStoreConfig(reqBody: UpdateStoreConfigRequest): Promise<void> {
    const fetchFn = this.options.fetch ?? globalThis.fetch;
    const response = await fetchFn(`${this.baseUrl}/UpdateStoreConfig`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...this.options.baseHeaders,
      },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      const error = new Error(`request failed: status=${response.status}, body=${text}`);
      this.options.onError?.(error, "UpdateStoreConfig");
      throw error;
    }

    await response.json();
  }

  async DeleteStoreConfig(reqBody: DeleteStoreConfigRequest): Promise<void> {
    const fetchFn = this.options.fetch ?? globalThis.fetch;
    const response = await fetchFn(`${this.baseUrl}/DeleteStoreConfig`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...this.options.baseHeaders,
      },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      const error = new Error(`request failed: status=${response.status}, body=${text}`);
      this.options.onError?.(error, "DeleteStoreConfig");
      throw error;
    }

    await response.json();
  }
}
