// Generated by gve api generate. Do not edit manually.

export interface StoreConfig {
  id: string;
  name: string;
  addr: string;
  description?: string;
  created_at: number;
  updated_at: number;
}

export interface CreateStoreConfigRequest {
  name: string;
  addr: string;
  description?: string;
}

export interface CreateStoreConfigResponse {
  config: StoreConfig;
}

export interface GetStoreConfigRequest {
  id: string;
}

export interface GetStoreConfigResponse {
  config: StoreConfig;
}

export interface ListStoreConfigsRequest {
}

export interface ListStoreConfigsResponse {
  list: StoreConfig[];
  total: number;
}

export interface UpdateStoreConfigRequest {
  id: string;
  name?: string;
  addr?: string;
  description?: string;
}

export interface DeleteStoreConfigRequest {
  id: string;
}
