// Code generated by hzx generator.
package v1

import (
	"context"

	baseV1 "datasource/apis/datasource/base/v1"
	v1 "datasource/apis/datasource/exporter/v1"
	configV1 "datasource/config/v1"
	websocket "datasource/internal/websocket"
	"datasource/pkg/exporter"

	"git.woa.com/castlexu/goutils/ablog"
)

var logger = ablog.NewLogger("exporter")

type ExporterHandler struct {
	cfg      *configV1.Config
	wsServer *websocket.Server
	manager  *exporter.Manager
}

func NewExporterHandler(cfg *configV1.Config, wsServer *websocket.Server, manager *exporter.Manager) *ExporterHandler {
	return &ExporterHandler{cfg: cfg, wsServer: wsServer, manager: manager}
}

// ListExporters
// @route /apis/v1/exporters [GET]
func (s *ExporterHandler) ListExporters(ctx context.Context, req *v1.ListExportersRequest) *baseV1.Response {
	filter := &exporter.Filter{
		AppID:    req.GetAppID(),
		Page:     req.GetPage(),
		PageSize: req.GetPageSize(),
	}

	// 处理状态过滤
	if req.IsSetState() {
		state := req.GetState()
		filter.State = &state
	}

	// 默认分页
	if filter.PageSize <= 0 {
		filter.PageSize = 20
	}
	if filter.Page <= 0 {
		filter.Page = 1
	}

	exporters, total := s.manager.ListExporters(filter)

	resp := &v1.ListExportersResponse{
		Exporters: exporters,
		Total:     total,
		Page:      &filter.Page,
		PageSize:  &filter.PageSize,
	}

	logger.Debug("list exporters: total=%d, page=%d, page_size=%d", total, filter.Page, filter.PageSize)
	
	// 打印实时的exporter详细信息
	logger.Debug("Exporter list details:")
	for i, exp := range exporters {
		logger.Debug("  [%d] ID=%s, AppID=%s, Instance=%s, State=%v, LastScrape=%d, ScrapeCount=%d",
			i+1, exp.GetID(), exp.GetAppID(), exp.GetInstance(), 
			exp.GetState(), exp.GetLastScrape(), exp.GetScrapeCount())
	}

	return baseV1.Success(baseV1.WithData(resp))
}

// GetExporter
// @route /apis/v1/exporters/:id [GET]
func (s *ExporterHandler) GetExporter(ctx context.Context, req *v1.GetExporterRequest) *baseV1.Response {
	exp := s.manager.GetExporter(req.GetID())
	if exp == nil {
		logger.Warn("Exporter not found - id=%s", req.GetID())
		return baseV1.Failed(nil, int64(baseV1.BaseErrorCode_NOT_FOUND))
	}

	resp := &v1.GetExporterResponse{
		Exporter: exp,
	}
	
	// 打印实时的exporter信息
	logger.Debug("Get exporter - ID=%s, AppID=%s, Instance=%s, State=%v, LastScrape=%d, ScrapeCount=%d, LastError=%v, Labels=%v",
		exp.GetID(), exp.GetAppID(), exp.GetInstance(), exp.GetState(), 
		exp.GetLastScrape(), exp.GetScrapeCount(), exp.GetLastError(), exp.GetLabels())

	return baseV1.Success(baseV1.WithData(resp))
}

// GetExporterStats
// @route /apis/v1/exporters/stats [GET]
func (s *ExporterHandler) GetExporterStats(ctx context.Context, req *v1.GetExporterStatsRequest) *baseV1.Response {
	var stats *v1.ExporterStats

	if req.GetAppID() != "" {
		stats = s.manager.GetStatsByAppID(req.GetAppID())
		logger.Debug("Get exporter stats for app_id=%s", req.GetAppID())
	} else {
		stats = s.manager.GetStats()
		logger.Debug("Get overall exporter stats")
	}

	resp := &v1.GetExporterStatsResponse{
		Stats: stats,
	}
	
	// 打印实时的exporter统计信息
	if stats != nil {
		logger.Debug("Exporter Stats - Total=%d, Up=%d, Down=%d, Unknown=%d",
			stats.GetTotal(), stats.GetUpCount(), stats.GetDownCount(), stats.GetUnknownCount())
	}

	return baseV1.Success(baseV1.WithData(resp))
}

// GetManager 返回 exporter manager，供其他 handler 使用
func (s *ExporterHandler) GetManager() *exporter.Manager {
	return s.manager
}
