
// Code generated by hzx generator. you can insert router here.
package v1

import (
	"datasource/internal/websocket"
	"github.com/cloudwego/hertz/pkg/app/server" 
)

func (s *ExporterService) Register(h *server.Hertz, wsServer *websocket.Server) {
	root := h.Group("/",rootMw()...)
	_apis := root.Group("/apis",_apisMw()...)
	_v1 := _apis.Group("/v1",_v1Mw()...)
	_v1.GET("/exporters", append(_listexportersMw(), s.ListExporters)...)
	_v1.GET("/exporters/:id", append(_getexporterMw(), s.GetExporter)...)
	_v1.GET("/exporters/stats", append(_getexporterstatsMw(), s.GetExporterStats)...)

	// websocket
	if wsServer != nil {
		// generate ws router code ... {topic}/{path} => s.handler.Ws{methodName}
	}
}
