// Code generated by hzx generator. DO NOT EDIT.
package hzapp

import (
	"context"
	"fmt"
	"net/http"
	"net/http/pprof"
	"time"

	ws "datasource/internal/websocket"

	// ...
	"git.woa.com/castlexu/goutils/ablog"
	"git.woa.com/castlexu/goutils/tools"
	"git.woa.com/castlexu/goutils/trigger"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/app/server/registry"
	hzconfig "github.com/cloudwego/hertz/pkg/common/config"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/cloudwego/hertz/pkg/route"
	"github.com/google/wire"
	consulapi "github.com/hashicorp/consul/api"
	"github.com/hertz-contrib/registry/consul"

	configV1 "datasource/config/v1"
	"datasource/internal/middleware"
	provider "datasource/internal/provider"
	"datasource/pkg/siteserver"
	"datasource/site"
)

var logger = ablog.NewLogger("hzapp")

var HzappSet = wire.NewSet(
	// HertzApp
	NewHertzApp,
)

type HertzApp struct {
	cfg            *configV1.Config
	server         *server.Hertz
	wsManager      *ws.Manager
	triggerManager *trigger.TriggerManager
	// 所有依赖包
	customDeps    *provider.CustomDeps
	generatedDeps *provider.GeneratedDeps
	triggerDeps   *provider.TriggerDeps
	bizDeps       *provider.BizDeps
	wsServer      *ws.Server
}

func NewHertzApp(cfg *configV1.Config,
	wsServer *ws.Server,
	wsManager *ws.Manager,
	triggerManager *trigger.TriggerManager,
	generatedDeps *provider.GeneratedDeps,
	triggerDeps *provider.TriggerDeps,
	bizDeps *provider.BizDeps,
	customDeps *provider.CustomDeps,
) *HertzApp {
	hlog.SetLevel(hlog.LevelWarn)
	opts := []hzconfig.Option{
		server.WithHostPorts(fmt.Sprintf(":%d", cfg.HertzServer.HttpPort)),
		server.WithKeepAliveTimeout(time.Duration(cfg.HertzServer.KeepAliveTimeout) * time.Second),
		server.WithIdleTimeout(time.Duration(cfg.HertzServer.IdleTimeout) * time.Second),
		server.WithReadTimeout(time.Duration(cfg.HertzServer.ReadTimeout) * time.Second),
		server.WithMaxRequestBodySize(cfg.HertzServer.MaxRequestBodySize),
		server.WithStreamBody(cfg.HertzServer.StreamBody),
		server.WithExitWaitTime(time.Duration(cfg.HertzServer.ExitWaitTime) * time.Second),
		server.WithMaxKeepBodySize(cfg.HertzServer.MaxKeepBodySize),
		server.WithKeepAlive(cfg.HertzServer.KeepAlive),
		server.WithReadBufferSize(cfg.HertzServer.ReadBufferSize),
	}

	// 如果启用consul，则添加consul注册
	if cfg.Consul.Enable {
		opts = append(opts, server.WithRegistry(newRegistry(cfg)))
	}

	h := server.New(opts...)

	h.GET("/health", func(ctx context.Context, c *app.RequestContext) {
		c.JSON(consts.StatusOK, utils.H{"code": 0, "message": "ok"})
	})

	// common middleware
	middleware.InstallMiddleware(h)

	// register websocket req
	h.GET("/ws", wsServer.HandleRequest)

	// generate register http services code ...
	for _, service := range bizDeps.Services {
		service.Register(h, wsServer)
	}

	// register websocket broadcasters
	wsManager.RegisterBroadcasters(bizDeps.Broadcasters...)

	triggerManager.RegisterTriggers(triggerDeps.Triggers...)

	// 注册静态文件服务（嵌入的前端资源）
	if err := siteserver.StaticFS(h, site.DistDirFS); err != nil {
		logger.Warn("Failed to register static file server: %v", err)
	}

	printRoutes(h)

	// ...
	return &HertzApp{
		cfg:            cfg,
		server:         h,
		wsManager:      wsManager,
		triggerManager: triggerManager,
		customDeps:     customDeps,
		generatedDeps:  generatedDeps,
		triggerDeps:    triggerDeps,
		bizDeps:        bizDeps,
		wsServer:       wsServer,
	}
}

func (h *HertzApp) Run() error {
	// start pprof server
	h.pprof()

	// start websocket server
	h.wsManager.StartServer()
	// start websocket broadcasters
	h.wsManager.StartBroadcasters()

	// start triggers
	h.triggerManager.StartAll()

	// start http server
	h.server.Spin()
	return nil
}

func (h *HertzApp) RegisterShutdown(shutdownFunc ...route.CtxCallback) error {
	shutdownFunc = append(shutdownFunc, func(ctx context.Context) {
		h.shutdown()
	})
	h.server.Engine.OnShutdown = append(h.server.Engine.OnShutdown, shutdownFunc...)
	return nil
}

func (h *HertzApp) GetCustomDeps() *provider.CustomDeps {
	return h.customDeps
}

func (h *HertzApp) GetGeneratedDeps() *provider.GeneratedDeps {
	return h.generatedDeps
}

func (h *HertzApp) GetTriggerDeps() *provider.TriggerDeps {
	return h.triggerDeps
}

func (h *HertzApp) GetBizDeps() *provider.BizDeps {
	return h.bizDeps
}

func (h *HertzApp) shutdown() {
	logger.Info("Shutting down HertzApp...")

	// 0. 停止 triggers
	h.triggerManager.StopAll()

	// 1. 停止 WebSocket 广播器
	h.wsManager.StopBroadcasters()

	// 2. 停止 WebSocket 服务器
	h.wsManager.StopServer()

	logger.Info("HertzApp shutdown complete")
}

func (h *HertzApp) pprof() {
	go func() {
		if h.cfg.HertzServer.PprofPort == 0 {
			return
		}
		logger.Info("(pprof) listen on %v", h.cfg.HertzServer.PprofPort)

		// Use pprof.Index to register all pprof routes at once
		// This avoids conflicts with automatically registered routes
		http.HandleFunc("/debug/pprof/", pprof.Index)

		// Start server after registering handlers
		http.ListenAndServe(fmt.Sprintf(":%d", h.cfg.HertzServer.PprofPort), nil)
	}()
}

func newRegistry(cfg *configV1.Config) (registry.Registry, *registry.Info) {
	if !cfg.Consul.Enable {
		return nil, nil
	}
	config := consulapi.DefaultConfig()
	config.Address = cfg.Consul.Address
	consulClient, err := consulapi.NewClient(config)
	if err != nil {
		logger.Fatal("new consul client error: %v", err)
		return nil, nil
	}

	// 自动获取当前服务地址(内网地址, kong能访问的到的地址即可)
	service_addr := fmt.Sprintf("%s:%d", tools.GetLocalIp(), cfg.HertzServer.HttpPort)
	// 配置HTTP健康检查
	check := &consulapi.AgentServiceCheck{
		HTTP:                           fmt.Sprintf("http://%s/health", service_addr),
		Timeout:                        cfg.Consul.HealthCheck.Timeout,
		Interval:                       cfg.Consul.HealthCheck.Interval,
		DeregisterCriticalServiceAfter: cfg.Consul.HealthCheck.DeregisterCriticalServiceAfter,
	}
	r := consul.NewConsulRegister(consulClient, consul.WithCheck(check))

	logger.Info("consul register success,service_name: %s, service_addr: %s", cfg.Consul.ServiceName, service_addr)

	return r, &registry.Info{
		ServiceName: cfg.Consul.ServiceName,
		Addr:        utils.NewNetAddr("tcp", service_addr),
		Weight:      cfg.Consul.Weight,
	}
}

func printRoutes(h *server.Hertz) {
	for _, route := range h.Engine.Routes() {
		logger.Info("Hertz Method=%-6s absolutePath=%-25s --> handler=%s", route.Method, route.Path, route.Handler)
	}
}
