// Generated by gve api generate. Do not edit manually.

import type { CreateSnapshotRequest, CreateSnapshotResponse, DeleteSnapshotRequest, GetSnapshotRequest, GetSnapshotResponse, ListSnapshotsRequest, ListSnapshotsResponse } from "./types";

/** Options for customizing client behavior. */
interface ClientOptions {
  fetch?: typeof globalThis.fetch;
  baseHeaders?: Record<string, string>;
  onError?: (error: Error, method: string) => void;
}

export class SnapshotServiceClient {
  private readonly baseUrl: string;
  private readonly options: ClientOptions;

  constructor(baseUrl: string, options?: ClientOptions) {
    this.baseUrl = baseUrl;
    this.options = options ?? {};
  }

  async CreateSnapshot(reqBody: CreateSnapshotRequest): Promise<CreateSnapshotResponse> {
    const fetchFn = this.options.fetch ?? globalThis.fetch;
    const response = await fetchFn(`${this.baseUrl}/CreateSnapshot`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...this.options.baseHeaders,
      },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      const error = new Error(`request failed: status=${response.status}, body=${text}`);
      this.options.onError?.(error, "CreateSnapshot");
      throw error;
    }

    return (await response.json()) as CreateSnapshotResponse;
  }

  async GetSnapshot(reqBody: GetSnapshotRequest): Promise<GetSnapshotResponse> {
    const fetchFn = this.options.fetch ?? globalThis.fetch;
    const response = await fetchFn(`${this.baseUrl}/GetSnapshot`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...this.options.baseHeaders,
      },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      const error = new Error(`request failed: status=${response.status}, body=${text}`);
      this.options.onError?.(error, "GetSnapshot");
      throw error;
    }

    return (await response.json()) as GetSnapshotResponse;
  }

  async ListSnapshots(reqBody: ListSnapshotsRequest): Promise<ListSnapshotsResponse> {
    const fetchFn = this.options.fetch ?? globalThis.fetch;
    const response = await fetchFn(`${this.baseUrl}/ListSnapshots`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...this.options.baseHeaders,
      },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      const error = new Error(`request failed: status=${response.status}, body=${text}`);
      this.options.onError?.(error, "ListSnapshots");
      throw error;
    }

    return (await response.json()) as ListSnapshotsResponse;
  }

  async DeleteSnapshot(reqBody: DeleteSnapshotRequest): Promise<void> {
    const fetchFn = this.options.fetch ?? globalThis.fetch;
    const response = await fetchFn(`${this.baseUrl}/DeleteSnapshot`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...this.options.baseHeaders,
      },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      const error = new Error(`request failed: status=${response.status}, body=${text}`);
      this.options.onError?.(error, "DeleteSnapshot");
      throw error;
    }

    await response.json();
  }
}
