// Generated by gve api generate. Do not edit manually.

export interface Snapshot {
  id: string;
  name: string;
  description?: string;
  tags: string[];
  app_id?: string;
  tap_ids: string[];
  start_time?: number;
  end_time?: number;
  status: string;
  error_msg?: string;
  chunk_count: number;
  total_bytes: number;
  created_at: number;
  updated_at: number;
}

export interface CreateSnapshotRequest {
  name: string;
  description?: string;
  tags?: string[];
  app_id?: string;
  tap_ids?: string[];
  start_time?: number;
  end_time?: number;
}

export interface CreateSnapshotResponse {
  snapshot: Snapshot;
}

export interface GetSnapshotRequest {
  id: string;
}

export interface GetSnapshotResponse {
  snapshot: Snapshot;
}

export interface ListSnapshotsRequest {
  app_id?: string;
}

export interface ListSnapshotsResponse {
  list: Snapshot[];
  total: number;
}

export interface DeleteSnapshotRequest {
  id: string;
}
