// Code generated by hzx generator.
package middleware

import (
	"context"
	"fmt"
	"net/url"
	"time"

	"git.woa.com/castlexu/goutils/ablog"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/google/uuid"
	"github.com/hertz-contrib/requestid"
)

var logger = ablog.NewLogger("request")

func InstallMiddleware(h *server.Hertz) {
	//
	h.Use([]app.HandlerFunc{
		// RequestFillerLogger(),
		recovery.Recovery(),
		requestid.New(
			requestid.WithGenerator(func(ctx context.Context, c *app.RequestContext) string {
				return "monitor_hub.hzx.io-" + uuid.New().String()
			}),
			// 自定义 request id 响应头键值
			requestid.WithCustomHeaderStrKey("X-Request-Id"),
			// define your request id handler here
			requestid.WithHandler(func(ctx context.Context, c *app.RequestContext, requestID string) {
				// 在请求处理之前执行的逻辑
				start := time.Now()
				// 继续处理请求
				c.Next(ctx)
				// 在请求处理之后执行的逻辑
				duration := time.Since(start)
				rtt_ms := duration.Milliseconds()
				rtt_μs := duration.Microseconds()
				rtt_ns := duration.Nanoseconds()

				var rtt_str string
				if rtt_ms > 0 {
					rtt_str = fmt.Sprintf("%vms", rtt_ms)
				} else if rtt_μs > 0 {
					rtt_str = fmt.Sprintf("%vμs", rtt_μs)
				} else {
					rtt_str = fmt.Sprintf("%vns", rtt_ns)
				}

				url_decoded, _ := url.QueryUnescape(string(c.Request.RequestURI()))
				statusCode := c.Response.StatusCode()

				// 4xx 和 5xx 才是错误，需要打印 body
				if statusCode >= 400 {
					logger.Error("(Middleware) X-Request-Id:(%v) %v %v rtt:(%v) status:(%v) body:(%v)",
						requestID,
						string(c.Request.Method()),
						url_decoded,
						rtt_str,
						statusCode,
						string(c.Request.Body()),
					)
				} else {
					// 2xx, 3xx, 101(WebSocket) 等都是正常状态
					logger.Debug("(Middleware) X-Request-Id:(%v) %v %v rtt:(%v) status:(%v)",
						requestID,
						string(c.Request.Method()),
						url_decoded,
						rtt_str,
						statusCode,
					)
				}
			}),
		),
	}...)
}
