// Code generated by wsocket-codegen. DO NOT EDIT.
package v1

import (
	"encoding/json"
)

// ============================================
// 结构体定义
// ============================================

type TriggerType string

const (
	TriggerTypeInterval TriggerType = "interval"
	TriggerTypeCron TriggerType = "cron"
	TriggerTypeEvent TriggerType = "event"
	TriggerTypeOnce TriggerType = "once"
)

// WsEnvelope WebSocket 消息包装器（传输层统一格式）
type WsEnvelope struct {
	Type string `json:"type"` // 消息类型：request/response/broadcast/heartbeat
	Topic string `json:"topic,omitempty"` // 资源主题（用于路由前缀和广播目标）
	Path string `json:"path,omitempty"` // 操作路径（相对于 topic 的路径）
	RequestId string `json:"request_id,omitempty"` // 请求ID（可选，用于匹配请求和响应）
	Data json.RawMessage `json:"data,omitempty"` // 业务数据（JSON 格式，由业务层定义具体结构）
	Timestamp int64 `json:"timestamp"` // 消息时间戳（Unix 时间戳，毫秒）
}

// WsResponse 通用响应数据（用于 request 的响应确认）
type WsResponse struct {
	Code int32 `json:"code"` // 响应码：0=成功，非0=失败
	Message string `json:"message"` // 响应描述
	Details string `json:"details,omitempty"` // 详细信息（可选）
	Data any `json:"data,omitempty"` // 响应业务数据（可选，JSON 格式）
}

// WsHeartbeat 心跳数据（用于 ping/pong 心跳检测）
type WsHeartbeat struct {
	ClientTime int64 `json:"client_time"` // 客户端时间戳（Unix 时间戳，毫秒）
	ServerTime int64 `json:"server_time,omitempty"` // 服务端时间戳（pong 时填充，ping 时为 0）
}

// BroadcastOption 广播选项
type BroadcastOption struct {
	Topic string `json:"topic"` // 主题
	Interval string `json:"interval"` // 间隔
	TriggerType TriggerType `json:"trigger_type"` // 触发类型
	Cron string `json:"cron,omitempty"` // cron 表达式
	OnceDelay string 
	EventName string `json:"event_name,omitempty"` // 事件名称
	Method string `json:"method"` // 方法
	EventBufferSize int `json:"event_buffer_size"` // 事件缓冲区大小
}
