// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package v1

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"math"
	"reflect"
)

type Opt func(*Response)

func WithData[T any](data ...T) Opt {
	return func(resp *Response) {
		if len(data) == 0 {
			return
		}
		if len(data) == 1 {
		    // 通过反射判断是否为数组类型，如果是，直接在这里展开
			rv := reflect.ValueOf(data[0])
			if rv.Kind() == reflect.Slice {
				resp.Data = make([]any, rv.Len())
				for i := 0; i < rv.Len(); i++ {
					resp.Data[i] = rv.Index(i).Interface()
				}
			} else {
				resp.Data = make([]any, 1)
				resp.Data[0] = data[0]
			}
			return
		}
		if resp.Data == nil {
			resp.Data = make([]any, len(data))
		}
		// 序列化处理转成字符串
		for i, v := range data {
			resp.Data[i] = v
		}
	}
}

func WithPage(page *Page) Opt {
	return func(resp *Response) {
		resp.Page = page
		if page.PageSize > 0 {
			resp.Page.TotalPage = int64(math.Ceil(float64(page.Total) / float64(page.PageSize))) // 向上取整
		}
	}
}

func ResponseSuccess(c *app.RequestContext, opts ...Opt) {
	resp := &Response{
		Msg: "success",
		Code: 0,
	}
	for _, opt := range opts {
		opt(resp)
	}
	c.JSON(consts.StatusOK, resp)
}

func ResponseFailed(c *app.RequestContext, err error, errorCode ...int64) {
	if len(errorCode) > 0 {
		c.JSON(consts.StatusOK, &Response{
			Data: nil,
			Msg:  err.Error(),
			Code: errorCode[0],
		})
		return
	}
	c.JSON(consts.StatusOK, &Response{
		Data: nil,
		Msg:  err.Error(),
		Code: -1,
	})
}

func Success(opts ...Opt) *Response {
	resp := &Response{
		Msg: "success",
		Code: 0,
	}
	for _, opt := range opts {
		opt(resp)
	}
	return resp
}

func Failed(err error, errorCode int64) *Response {
	return &Response{
		Data: nil,
		Msg:  err.Error(),
		Code: errorCode,
	}
}
