// Generated by gve api generate. Do not edit manually.
package snapshot

type Snapshot struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	Tags []string `json:"tags"`
	AppID string `json:"app_id,omitempty"`
	TapIds []string `json:"tap_ids"`
	StartTime int64 `json:"start_time,omitempty"`
	EndTime int64 `json:"end_time,omitempty"`
	Status string `json:"status"`
	ErrorMsg string `json:"error_msg,omitempty"`
	ChunkCount int32 `json:"chunk_count"`
	TotalBytes int64 `json:"total_bytes"`
	CreatedAt int64 `json:"created_at"`
	UpdatedAt int64 `json:"updated_at"`
}

type CreateSnapshotRequest struct {
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	Tags []string `json:"tags,omitempty"`
	AppID string `json:"app_id,omitempty"`
	TapIds []string `json:"tap_ids,omitempty"`
	StartTime int64 `json:"start_time,omitempty"`
	EndTime int64 `json:"end_time,omitempty"`
}

type CreateSnapshotResponse struct {
	Snapshot Snapshot `json:"snapshot"`
}

type GetSnapshotRequest struct {
	ID string `json:"id"`
}

type GetSnapshotResponse struct {
	Snapshot Snapshot `json:"snapshot"`
}

type ListSnapshotsRequest struct {
	AppID string `json:"app_id,omitempty"`
}

type ListSnapshotsResponse struct {
	List []Snapshot `json:"list"`
	Total int32 `json:"total"`
}

type DeleteSnapshotRequest struct {
	ID string `json:"id"`
}
