// Code generated by hzx generator.
package middleware

import (
	"context"
	"fmt"
	"net/url"
	"time"

	"git.woa.com/castlexu/goutils/ablog"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/google/uuid"
	"github.com/hertz-contrib/requestid"
)

var logger = ablog.NewLogger("request")

func InstallMiddleware(h *server.Hertz) {
	//
	h.Use([]app.HandlerFunc{
		// RequestFillerLogger(),
		recovery.Recovery(),
		requestid.New(
			requestid.WithGenerator(func(ctx context.Context, c *app.RequestContext) string {
				return "datasource.hzx.io-" + uuid.New().String()
			}),
			// 自定义 request id 响应头键值
			requestid.WithCustomHeaderStrKey("X-Request-Id"),
			// define your request id handler here
			requestid.WithHandler(func(ctx context.Context, c *app.RequestContext, requestID string) {
				// 在请求处理之前执行的逻辑
				start := time.Now()
				// 继续处理请求
				c.Next(ctx)
				// 在请求处理之后执行的逻辑
				duration := time.Since(start)
				rtt_ms := duration.Milliseconds()
				rtt_μs := duration.Microseconds()
				rtt_ns := duration.Nanoseconds()

				var rtt_str string
				if rtt_ms > 0 {
					rtt_str = fmt.Sprintf("%vms", rtt_ms)
				} else if rtt_μs > 0 {
					rtt_str = fmt.Sprintf("%vμs", rtt_μs)
				} else {
					rtt_str = fmt.Sprintf("%vns", rtt_ns)
				}

				url_decoded, _ := url.QueryUnescape(string(c.Request.RequestURI()))
				// 如果是400,打印客户端请求的body
				if c.Response.StatusCode() != 200 {
					logger.Error("<X-Request-Id:%v> %v %v rtt:%v status:%v body:%v",
						requestID,
						string(c.Request.Method()),
						url_decoded,
						rtt_str,
						c.Response.StatusCode(), // 添加状态码日志
						string(c.Request.Body()),
					)
				} else {
					logger.Debug("<X-Request-Id:%v> %v %v rtt:%v status:%v",
						requestID,
						string(c.Request.Method()),
						url_decoded,
						rtt_str,
						c.Response.StatusCode(), // 添加状态码日志
					)
				}
			}),
		),
	}...)
}
