
// Code generated by hzx generator. you can insert router here.
package v1

import (
	"monitor_hub/internal/websocket"
	"github.com/cloudwego/hertz/pkg/app/server" 
)

func (s *PointsService) Register(h *server.Hertz, wsServer *websocket.Server) {
	root := h.Group("/",rootMw()...)
	_apis := root.Group("/apis",_apisMw()...)
	_v1 := _apis.Group("/v1",_v1Mw()...)
	_points := _v1.Group("/points",_pointsMw()...)
	_points.POST("/query", append(_querypointsMw(), s.QueryPoints)...)

	// websocket
	if wsServer != nil {
		// generate ws router code ... {topic}/{path} => s.handler.Ws{methodName}
		wsServer.HandleFunc("points/subscribe", s.handler.WsSubscribePoints)
		wsServer.HandleFunc("points/unsubscribe", s.handler.WsUnsubscribePoints)
	}
}
