// Code generated by hzx generator. DO NOT EDIT.
package v1

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	v1 "monitor_hub/apis/monitor_hub/points/v1"
	baseV1 "monitor_hub/apis/monitor_hub/base/v1"
)

type PointsService struct {
	handler *PointsHandler
}

func NewPointsService(handler *PointsHandler) *PointsService {
	return &PointsService{handler:handler}
}

// QueryPoints
// @route /apis/v1/points/query [POST]
func (s *PointsService) QueryPoints(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.QueryPointsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.QueryPoints(ctx, &req))
}

