// Code generated by Validator v0.2.6. DO NOT EDIT.

package v1

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *TestTask) IsValid() error {
	return nil
}
func (p *CreateTaskRequest) IsValid() error {
	if p.Task == nil {
		return fmt.Errorf("field Task not_nil rule failed")
	}
	if err := p.Task.IsValid(); err != nil {
		return fmt.Errorf("field Task not valid, %w", err)
	}
	return nil
}
func (p *UpdateTaskRequest) IsValid() error {
	if len(p.ID) < int(1) {
		return fmt.Errorf("field ID min_len rule failed, current value: %d", len(p.ID))
	}
	if p.Task == nil {
		return fmt.Errorf("field Task not_nil rule failed")
	}
	if err := p.Task.IsValid(); err != nil {
		return fmt.Errorf("field Task not valid, %w", err)
	}
	return nil
}
func (p *UploadIconRequest) IsValid() error {
	if len(p.TaskID) < int(1) {
		return fmt.Errorf("field TaskID min_len rule failed, current value: %d", len(p.TaskID))
	}
	if len(p.IconData) < int(1) {
		return fmt.Errorf("field IconData min_len rule failed, current value: %d", len(p.IconData))
	}
	if len(p.FileName) < int(1) {
		return fmt.Errorf("field FileName min_len rule failed, current value: %d", len(p.FileName))
	}
	if len(p.FileName) > int(100) {
		return fmt.Errorf("field FileName max_len rule failed, current value: %d", len(p.FileName))
	}
	return nil
}
func (p *ForwardTaskRequest) IsValid() error {
	if len(p.TargetURL) < int(1) {
		return fmt.Errorf("field TargetURL min_len rule failed, current value: %d", len(p.TargetURL))
	}
	if len(p.TaskID) < int(1) {
		return fmt.Errorf("field TaskID min_len rule failed, current value: %d", len(p.TaskID))
	}
	return nil
}
