// Code generated by Validator v0.2.6. DO NOT EDIT.

package v1

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *QueryPointFilter) IsValid() error {
	return nil
}
func (p *QueryPointsRequest) IsValid() error {
	if len(p.DatasourceID) < int(1) {
		return fmt.Errorf("field DatasourceID min_len rule failed, current value: %d", len(p.DatasourceID))
	}
	if len(p.DatasourceID) > int(100) {
		return fmt.Errorf("field DatasourceID max_len rule failed, current value: %d", len(p.DatasourceID))
	}
	if len(p.Levels) < int(1) {
		return fmt.Errorf("field Levels MinLen rule failed, current value: %v", p.Levels)
	}
	if len(p.Levels) > int(10) {
		return fmt.Errorf("field Levels MaxLen rule failed, current value: %v", p.Levels)
	}
	if p.StartTime != nil {
		if *p.StartTime < int64(0) {
			return fmt.Errorf("field StartTime ge rule failed, current value: %v", *p.StartTime)
		}
	}
	if p.EndTime != nil {
		if *p.EndTime < int64(0) {
			return fmt.Errorf("field EndTime ge rule failed, current value: %v", *p.EndTime)
		}
	}
	if p.Limit != nil {
		if *p.Limit < int32(1) {
			return fmt.Errorf("field Limit ge rule failed, current value: %v", *p.Limit)
		}
		if *p.Limit > int32(100000) {
			return fmt.Errorf("field Limit le rule failed, current value: %v", *p.Limit)
		}
	}
	if p.DataStatus != nil {
		_src := []string{string("complete"), string("partial"), string("degraded"), string("missing")}
		var _exist bool
		for _, src := range _src {
			if *p.DataStatus == src {
				_exist = true
				break
			}
		}
		if !_exist {
			return fmt.Errorf("field DataStatus in rule failed, current value: %v", *p.DataStatus)
		}
	}
	if len(p.AggregationTypes) > int(5) {
		return fmt.Errorf("field AggregationTypes MaxLen rule failed, current value: %v", p.AggregationTypes)
	}
	return nil
}
func (p *SummaryTable) IsValid() error {
	return nil
}
