// Code generated by wsocket-codegen. DO NOT EDIT.
package v1

import (
	"context"
	baseV1 "monitor_hub/apis/monitor_hub/base/v1"
	"github.com/bytedance/go-tagexpr/v2/validator"
)

// ============================================
// 结构体定义
// ============================================

// DataQuality 数据质量信息
type DataQuality struct {
	ActualPoints int32 `json:"actual_points,omitempty" bson:"actual_points" vt:"gte:'0'"` // 实际采样点数
	ExpectedPoints int32 `json:"expected_points,omitempty" bson:"expected_points" vt:"gte:'0'"` // 期望采样点数
	Score float64 `json:"score" bson:"score" vt:"gte:'0',lte:'100'"` // 质量分数（0-100），100表示完整数据，0表示无数据
	Status string `json:"status" bson:"status"` // 数据状态：complete(完整) / partial(部分) / degraded(降级) / missing(缺失)
	MissingReason string `json:"missing_reason,omitempty" bson:"missing_reason"` // 数据缺失/降级原因
}

// IsValid 验证结构体字段
func (m *DataQuality) IsValid() error {
	return validator.Validate(m)
}

// AggregatedPoint 单个聚合数据点（扁平化结构，每个聚合类型对应一个数据点）
type AggregatedPoint struct {
	DatasourceId string `json:"datasource_id" bson:"datasource_id" vt:"min_size:'1'"` // 数据源ID
	Name string `json:"name" bson:"name" vt:"min_size:'1',max_size:'200'"` // 指标名称
	Labels []string `json:"labels" bson:"labels"` // 标签集合（包含 __aggregation_level__、__statistic_suffix__ 等内部标签）
	Level string `json:"level" bson:"level" vt:"min_size:'1'"` // 聚合级别：15s/1m/5m/15m/1h/6h/1d
	Timestamp int64 `json:"timestamp" bson:"timestamp" vt:"gt:'0'"` // 时间戳（Unix 毫秒，对齐到级别边界）
	Date string `json:"date,omitempty" bson:"date"` // 日期（调试查看使用）
	AggregationType string `json:"aggregation_type" bson:"aggregation_type" vt:"in:'avg,min,max,count,last'"` // 聚合类型：avg/min/max/count/last
	Value float64 `json:"value" bson:"value"` // 聚合后的值
	Quality DataQuality `json:"quality" bson:"quality"` // 数据质量信息
}

// IsValid 验证结构体字段
func (m *AggregatedPoint) IsValid() error {
	return validator.Validate(m)
}

// SubscribePointsRequest 订阅实时聚合数据推送（推荐订阅小级别：15s、1m、5m）
type SubscribePointsRequest struct {
	DatasourceId string `json:"datasource_id" vt:"min_size:'1'"` // 数据源ID
	AggregationLevels []string `json:"aggregation_levels" vt:"min_size:'1'"` // 要订阅的聚合等级列表（如 ['15s', '1m']）
	MetricFilters []string `json:"metric_filters,omitempty"` // 指标名称过滤（可选，为空表示订阅所有指标）
	Labels []string `json:"labels,omitempty"` // 标签过滤条件（可选，支持精确匹配）
}

// IsValid 验证结构体字段
func (m *SubscribePointsRequest) IsValid() error {
	return validator.Validate(m)
}

// UnsubscribePointsRequest 取消订阅请求
type UnsubscribePointsRequest struct {
	DatasourceId string `json:"datasource_id"` // 数据源ID
	AggregationLevels []string `json:"aggregation_levels,omitempty"` // 要取消的聚合等级（为空表示取消该数据源的所有订阅）
}

// PointsBroadcast 实时推送聚合数据更新（所有信息都在 points 中）
type PointsBroadcast struct {
	Points []AggregatedPoint `json:"points"` // 聚合数据点列表（每个点包含完整信息：datasource_id, level, timestamp 等）
	Count int32 `json:"count"` // 数据点数量
}

// ============================================
// Service 定义
// ============================================

var Default_WsPointsOptions = []baseV1.BroadcastOption{
	{
		TriggerType:  baseV1.TriggerTypeEvent,
		Topic:        "points",
		EventName:    "aggregation.*",
		Method:    	  "BroadcastPoints",
		EventBufferSize: 4096,
	},

}

type WsPointsPointsTopic interface {
	SubscribePoints(ctx context.Context, req *SubscribePointsRequest) (*baseV1.WsResponse, error)
	UnsubscribePoints(ctx context.Context, req *UnsubscribePointsRequest) (*baseV1.WsResponse, error)
	BroadcastPoints(ctx context.Context) (*PointsBroadcast, error)
}
/* 
TODO: 暂时有些问题，而且没有被项目应用，先注释掉
var Default_WsPointsPointsTopic = &WsPointsPointsTopicImpl{}

type WsPointsPointsTopicImpl struct{}

func (t *WsPointsPointsTopicImpl) Topic() string {
	return "points"
}

func (t *WsPointsPointsTopicImpl) Trigger() string {
	return "event"
}

func (t *WsPointsPointsTopicImpl) EventName() string {
	return "aggregation.*"
}

func (t *WsPointsPointsTopicImpl) Method() string {
	return "BroadcastPoints"
} */
