// Code generated by hzx generator. DO NOT EDIT.
package app

import (
	"context"
	"sync"

	configV1 "datasource/config/v1"
	"datasource/internal/hzapp"

	"git.woa.com/castlexu/goutils/ablog"
	"github.com/cloudwego/hertz/pkg/route"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

var configFilePath string

// AppContext 应用上下文，包含 Context 和 Cancel 函数
type AppContext struct {
	Context context.Context
	Cancel  context.CancelFunc
}

type DatasourceApp struct {
	logger *ablog.Logger
	hzapp  *hzapp.HertzApp
	cfg    *configV1.Config
	cancel context.CancelFunc
	wg     *sync.WaitGroup
}

func initCobraFlags(fs *pflag.FlagSet) {
	fs.StringVarP(&configFilePath, "config", "c", "config.yaml", "datasource config file .")
}

func newDatasourceApp(
	appCtx *AppContext,
	cfg *configV1.Config,
	wg *sync.WaitGroup,
	hzapp *hzapp.HertzApp,
) *DatasourceApp {
	return &DatasourceApp{
		logger: ablog.NewLogger("datasource-app"),
		hzapp:  hzapp,
		cfg:    cfg,
		cancel: appCtx.Cancel, // 从 AppContext 中获取 cancel 函数
		wg:     wg,
	}
}

func NewServerCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:  "datasource",
		Long: "Hertz Micro Service for Http Server",
		RunE: func(cmd *cobra.Command, args []string) error {
			return Run()
		},
		Args: func(cmd *cobra.Command, args []string) error {
			return nil
		},
	}
	initCobraFlags(cmd.PersistentFlags())
	return cmd
}

func Run() error {
	app, err := New(configFilePath)
	if err != nil {
		return err
	}
	app.registerShutdownFunction()
	return app.hzapp.Run()
}

func (a *DatasourceApp) registerShutdownFunction() {
	a.hzapp.RegisterShutdown(
		route.CtxCallback(func(ctx context.Context) {
			a.logger.Info("Shutting down application...")

			// 1. 取消 context，触发所有触发器停止
			if a.cancel != nil {
				a.cancel()
				a.logger.Info("Cancelled context, waiting for triggers to stop...")
			}

			// 2. 等待所有触发器的 goroutine 结束 TODO 可能需要增加超时检测
			a.wg.Wait()
			a.logger.Info("All triggers stopped")

			// 优雅关闭tsdb存储
			a.hzapp.GetCustomDeps().MetricPointStorage.Close()

			// 3. 优雅关闭由 HzApp 统一处理（WebSocket 等）
			a.logger.Info("Application shutdown complete")
		}),
	)
}

func (a *DatasourceApp) PrepareRun(ctx context.Context) error {
	// Custom : 这里可以通过a.hzapp获取到所有内置的依赖包， 用来初始化或运行你的自定义依赖
	return nil
}
