//go:build wireinject
// +build wireinject

// Code generated by hzx generator. DO NOT EDIT.
package app

import (
	"context"
	"sync"

	"datasource/internal/hzapp"
	"datasource/internal/provider"
	"datasource/internal/websocket"

	"git.woa.com/castlexu/goutils/trigger"
	"github.com/google/wire"
)

// ProvideAppContext 提供应用的可取消 Context
// AppContext 定义在 app.go 中
func ProvideAppContext() *AppContext {
	ctx, cancel := context.WithCancel(context.Background())
	return &AppContext{
		Context: ctx,
		Cancel:  cancel,
	}
}

// ProvideContext 从 AppContext 中提取 Context 供触发器使用
func ProvideContext(appCtx *AppContext) context.Context {
	return appCtx.Context
}

// ProvideWaitGroup 提供 WaitGroup 用于等待所有触发器的 goroutine
func ProvideWaitGroup() *sync.WaitGroup {
	return &sync.WaitGroup{}
}

// ProvideWSServer 提供 WebSocket Server
func ProvideWSServer(wsManager *websocket.Manager) *websocket.Server {
	return wsManager.GetWSServer()
}

func New(configFilePath string) (*DatasourceApp, error) {
	panic(wire.Build(
		ProvideAppContext, // 创建 AppContext（包含 ctx 和 cancel）
		ProvideContext,    // 提取 context.Context 给触发器用
		ProvideWaitGroup,

		provider.GeneratedProviderSet, // 基础依赖：config, mongodb, repo

		provider.CustomProviderSet, // 自定义依赖

		provider.TriggerProviderSet, // 触发器依赖

		// Trigger Manager
		trigger.NewTriggerManager,

		// WebSocket Manager
		websocket.NewManager,
		// WebSocket Server
		ProvideWSServer,

		// 允许biz业务以来上层依赖包, 所以要放在下面
		provider.BizProviderSet, // 业务依赖：handler, service, broadcaster

		hzapp.HzappSet,
		newDatasourceApp,
	))
}
