// Code generated by wsocket-codegen. DO NOT EDIT.
package v1

import (
	"context"
	baseV1 "monitor_hub/apis/monitor_hub/base/v1"
	"github.com/bytedance/go-tagexpr/v2/validator"
)

// ============================================
// 结构体定义
// ============================================

// AddressStatus 单个 Pushgateway 地址的状态信息
type AddressStatus struct {
	Address string `json:"address" bson:"address" vt:"min_size:'1'"` // 地址（host:port）
	Status string `json:"status" bson:"status" vt:"in:'online,offline'"` // 状态：online / offline
	LatencyMs int32 `json:"latency_ms" bson:"latency_ms" vt:"gte:'0'"` // 响应延迟（毫秒），offline 时为 0
	ErrorMessage string `json:"error_message,omitempty" bson:"error_message" vt:"max_size:'500'"` // 错误信息（仅在 offline 时有值）
	LastOnlineTime int64 `json:"last_online_time,omitempty" bson:"last_online_time"` // 最后一次在线时间（Unix 时间戳，秒）
	TotalSeries int64 `json:"total_series,omitempty" bson:"total_series"` // 总序列数
	DiskSize int64 `json:"disk_size,omitempty" bson:"disk_size"` // 磁盘占用大小（字节）
	RetentionDays int32 `json:"retention_days,omitempty" bson:"retention_days"` // 数据保留天数
	TotalSamples int64 `json:"total_samples,omitempty" bson:"total_samples"` // 采样点总数
}

// IsValid 验证结构体字段
func (m *AddressStatus) IsValid() error {
	return validator.Validate(m)
}

// DatasourceStatus 单个数据源的完整状态信息
type DatasourceStatus struct {
	DatasourceId string `json:"datasource_id" bson:"datasource_id" vt:"min_size:'1'"` // 数据源ID
	Name string `json:"name" bson:"name" vt:"min_size:'1',max_size:'100'"` // 数据源名称
	AppId string `json:"app_id" bson:"app_id" vt:"min_size:'1',max_size:'50'"` // 项目标识
	Addresses []AddressStatus `json:"addresses" bson:"addresses" vt:"min_size:'1'"` // 所有 Pushgateway 地址的状态
	OverallStatus string `json:"overall_status" bson:"overall_status" vt:"in:'healthy,degraded,down'"` // 整体状态：healthy(全部在线) / degraded(部分在线) / down(全部离线)
	HealthyCount int32 `json:"healthy_count" bson:"healthy_count" vt:"gte:'0'"` // 健康的地址数量
	TotalCount int32 `json:"total_count" bson:"total_count" vt:"gte:'1'"` // 总地址数量
	LastCheckTime int64 `json:"last_check_time" bson:"last_check_time"` // 最后检查时间（Unix 时间戳，秒）
}

// IsValid 验证结构体字段
func (m *DatasourceStatus) IsValid() error {
	return validator.Validate(m)
}

// SubscribeDatasourceStatusRequest 订阅数据源状态更新的请求参数
type SubscribeDatasourceStatusRequest struct {
	DatasourceIds []string `json:"datasource_ids,omitempty"` // 要订阅的数据源ID列表，空列表或不传表示订阅全部
	IncludeDetails bool `json:"include_details,omitempty"` // 是否包含详细信息（如每个地址的状态）
}

// DatasourceStatusBroadcast 推送数据源状态更新
type DatasourceStatusBroadcast struct {
	Updates []DatasourceStatus `json:"updates" vt:"not_nil:'true'"` // 更新的数据源状态列表
}

// IsValid 验证结构体字段
func (m *DatasourceStatusBroadcast) IsValid() error {
	return validator.Validate(m)
}

// UnsubscribeRequest 取消订阅请求
type UnsubscribeRequest struct {
	Topic string `json:"topic" vt:"min_size:'1'"` // 要取消订阅的主题
}

// IsValid 验证结构体字段
func (m *UnsubscribeRequest) IsValid() error {
	return validator.Validate(m)
}

// ============================================
// Service 定义
// ============================================

var Default_WsDatasourceOptions = []baseV1.BroadcastOption{
	{
		TriggerType:  baseV1.TriggerTypeInterval,
		Topic:        "datasource.status",
		Interval:     "10s",
		Method:    	  "BroadcastDatasourceStatus",
	},

}

type WsDatasourceStatusTopic interface {
	SubscribeDatasourceStatus(ctx context.Context, req *SubscribeDatasourceStatusRequest) (*baseV1.WsResponse, error)
	UnsubscribeDatasourceStatus(ctx context.Context, req *UnsubscribeRequest) (*baseV1.WsResponse, error)
	BroadcastDatasourceStatus(ctx context.Context) (*DatasourceStatusBroadcast, error)
}
/* 
TODO: 暂时有些问题，而且没有被项目应用，先注释掉
var Default_WsDatasourceStatusTopic = &WsDatasourceStatusTopicImpl{}

type WsDatasourceStatusTopicImpl struct{}

func (t *WsDatasourceStatusTopicImpl) Topic() string {
	return "datasource.status"
}

func (t *WsDatasourceStatusTopicImpl) Trigger() string {
	return "interval"
}

func (t *WsDatasourceStatusTopicImpl) Interval() string {
	return "10s"
}

func (t *WsDatasourceStatusTopicImpl) Method() string {
	return "BroadcastDatasourceStatus"
} */
