// Code generated by hzx generator. you can insert middleware here.
package v1

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}
func _metricsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reportmetricsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querymetricsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getstatsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apisMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}


