
// Code generated by hzx generator. you can insert router here.
package v1

import (
	"datasource/internal/websocket"
	"github.com/cloudwego/hertz/pkg/app/server" 
)

func (s *MetricsService) Register(h *server.Hertz, wsServer *websocket.Server) {
	root := h.Group("/",rootMw()...)
	_apis := root.Group("/apis",_apisMw()...)
	_v1 := _apis.Group("/v1",_v1Mw()...)
	_metrics := _v1.Group("/metrics",_metricsMw()...)
	_metrics.POST("/batch", append(_reportmetricsMw(), s.ReportMetrics)...)
	_metrics.POST("/query", append(_querymetricsMw(), s.QueryMetrics)...)
	_metrics.POST("/query_stats", append(_getstatsMw(), s.GetStats)...)

	// websocket
	if wsServer != nil {
		// generate ws router code ... {topic}/{path} => s.handler.Ws{methodName}
	}
}
