// Code generated by hzx generator. DO NOT EDIT.
package provider

import (
	"git.woa.com/castlexu/goutils/trigger"
	"github.com/google/wire"
	// ... ↓ 导入用户自定义触发器
)

var TriggerProviderSet = wire.NewSet(
	// ... ↓ 这里添加
	ProvideTriggerDeps,
)

type TriggerDeps struct {
	Triggers []trigger.Trigger
}

func ProvideTriggerDeps(
// ... ↓ 添加触发器依赖
) *TriggerDeps {
	return &TriggerDeps{
		Triggers: []trigger.Trigger{
			// ... ↓ 添加触发器依赖
		},
	}
}
