// Code generated by Validator v0.2.6. DO NOT EDIT.

package v1

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *SetMarkExpiredRequest) IsValid() error {
	if len(p.StressID) < int(1) {
		return fmt.Errorf("field StressID min_len rule failed, current value: %d", len(p.StressID))
	}
	return nil
}
func (p *MarkList) IsValid() error {
	return nil
}
func (p *Mark) IsValid() error {
	if len(p.AppID) < int(1) {
		return fmt.Errorf("field AppID min_len rule failed, current value: %d", len(p.AppID))
	}
	if len(p.StressID) < int(1) {
		return fmt.Errorf("field StressID min_len rule failed, current value: %d", len(p.StressID))
	}
	return nil
}
func (p *RequestMetrics) IsValid() error {
	return nil
}
func (p *StressMetricsItem) IsValid() error {
	return nil
}
func (p *ListMarkResponse) IsValid() error {
	return nil
}
