package metrics

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

// MetricsServiceHTTPClient is generated by gve api generate.
type MetricsServiceHTTPClient struct {
	baseURL string
	http    *http.Client
}

func NewMetricsServiceHTTPClient(baseURL string, httpClient *http.Client) *MetricsServiceHTTPClient {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	return &MetricsServiceHTTPClient{baseURL: baseURL, http: httpClient}
}

func (c *MetricsServiceHTTPClient) ReportMetrics(ctx context.Context, reqBody any) (json.RawMessage, error) {
	payload, err := json.Marshal(reqBody)
	if err != nil {
		return nil, fmt.Errorf("marshal request: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.baseURL+"/ReportMetrics", bytes.NewReader(payload))
	if err != nil {
		return nil, fmt.Errorf("new request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("send request: %w", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if resp.StatusCode >= http.StatusBadRequest {
		return nil, fmt.Errorf("request failed: status=%d body=%s", resp.StatusCode, string(body))
	}

	return json.RawMessage(body), nil
}

func (c *MetricsServiceHTTPClient) QueryMetrics(ctx context.Context, reqBody any) (json.RawMessage, error) {
	payload, err := json.Marshal(reqBody)
	if err != nil {
		return nil, fmt.Errorf("marshal request: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.baseURL+"/QueryMetrics", bytes.NewReader(payload))
	if err != nil {
		return nil, fmt.Errorf("new request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("send request: %w", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if resp.StatusCode >= http.StatusBadRequest {
		return nil, fmt.Errorf("request failed: status=%d body=%s", resp.StatusCode, string(body))
	}

	return json.RawMessage(body), nil
}

