// Code generated by hzx generator.
package v1

import (
	"bytes"
	"context"
	"fmt"
	"io"
	baseV1 "monitor_hub/apis/monitor_hub/base/v1"
	pointsV1 "monitor_hub/apis/monitor_hub/points/v1"
	reportV1 "monitor_hub/apis/monitor_hub/report/v1"
	pushgatewayV1 "monitor_hub/apis/pushgateway/metrics/v1"
	configV1 "monitor_hub/config/v1"
	websocket "monitor_hub/internal/websocket"
	pkgaggregator "monitor_hub/pkg/aggregator"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"monitor_hub/pkg/cache"
	"monitor_hub/pkg/dataprocess"
	"monitor_hub/pkg/repo"
	"monitor_hub/pkg/scoring"
	"monitor_hub/pkg/taskpool"
	"monitor_hub/pkg/utils"

	"git.woa.com/castlexu/goutils/ablog"
	"git.woa.com/castlexu/goutils/tools"
	"github.com/bytedance/sonic"
)

var logger = ablog.NewLogger("report-handler")

// MongoDB 单文档最大 16MB，预留 2MB 给其他字段和 BSON 编码开销
const maxChunkPartSize = 14 * 1024 * 1024 // 14MB

// getCaseChunkIDs 获取 case 的所有 chunk IDs（兼容新旧格式）
// 优先使用新的 chunk_ids 字段，若为空则回退到旧的 chunk_id 字段
func getCaseChunkIDs(singleCase *reportV1.SingleCase) []string {
	if ids := singleCase.GetChunkIDs(); len(ids) > 0 {
		return ids
	}
	if id := singleCase.GetChunkID(); id != "" {
		return []string{id}
	}
	return nil
}

// setCaseChunkIDs 同时设置新旧字段（确保向后兼容）
func setCaseChunkIDs(singleCase *reportV1.SingleCase, chunkIDs []string) {
	singleCase.ChunkIDs = chunkIDs
	// 同时设置旧字段，兼容旧版前端和转发场景
	if len(chunkIDs) > 0 {
		singleCase.ChunkID = &chunkIDs[0]
	} else {
		singleCase.ChunkID = nil
	}
}

type chunkDataWithInfo struct {
	chunkData
	OriginalSize int64 `json:"original_size"`
	PointCount   int32 `json:"point_count"`
	MetricCount  int32 `json:"metric_count"`
}

type chunkData struct {
	Tables []*dataprocess.SummaryTable `json:"t"`
	Points *dataprocess.PointsResponse `json:"p"`
}

type timeWindow struct {
	startTime int64
	endTime   int64
}

type ReportHandler struct {
	cfg            *configV1.Config
	wsServer       *websocket.Server
	datasourceRepo repo.DatasourceRepo
	reportRepo     repo.ReportRepo
	taskPool       *taskpool.TaskPool
	collector      pkgaggregator.Collector
	chunkCache     *cache.Cache[chunkDataWithInfo]
}

func NewReportHandler(
	cfg *configV1.Config,
	wsServer *websocket.Server,
	datasourceRepo repo.DatasourceRepo,
	reportRepo repo.ReportRepo,
	collector pkgaggregator.Collector,
) *ReportHandler {
	return &ReportHandler{
		cfg:            cfg,
		wsServer:       wsServer,
		datasourceRepo: datasourceRepo,
		reportRepo:     reportRepo,
		taskPool: taskpool.New(
			taskpool.WithMaxWorkers(cfg.Taskpool.MaxWorkers),
			taskpool.WithTaskTimeout(tools.ParseDuration(cfg.Taskpool.TaskTimeout)),
			taskpool.WithMaxTaskHistory(cfg.Taskpool.MaxTaskHistory),
		),
		collector: collector,
		chunkCache: cache.NewCache[chunkDataWithInfo](
			cache.WithMaxSize(cfg.ChunkCache.MaxSize),
			cache.WithDefaultTTL(tools.ParseDuration(cfg.ChunkCache.DefaultTtl)),
		),
	}
}

// CreateReport
// @route /apis/v1/report/create [POST]
func (s *ReportHandler) CreateReport(ctx context.Context, req *reportV1.Report) *baseV1.Response {
	// 1. 参数校验
	if req.GetName() == "" {
		return baseV1.Failed(fmt.Errorf("报告名称不能为空"), 1001) // INVALID_PARAM
	}
	if len(req.GetCases()) == 0 {
		return baseV1.Failed(fmt.Errorf("至少需要一个测试用例"), 1001) // INVALID_PARAM
	}
	// 校验 extra_info：必须是偶数个元素（key-value 对）
	if extraInfo := req.GetExtraInfo(); extraInfo != nil && len(extraInfo)%2 != 0 {
		return baseV1.Failed(fmt.Errorf("extra_info 必须是偶数个元素（key-value 对），当前为 %d 个", len(extraInfo)), 1001) // INVALID_PARAM
	}

	// 1.1 查询数据源配置
	datasource, err := s.datasourceRepo.GetDatasource(ctx, req.GetDatasourceID())
	if err != nil {
		return baseV1.Failed(fmt.Errorf("数据源查询失败: %v", err), int64(baseV1.BaseErrorCode_NOT_FOUND))
	}

	// 2. 先创建报告记录（获取 reportID）
	req.ReportStatus = &reportV1.ReportStatus{
		Status: string(taskpool.TaskStatusRunning),
	}
	appID := datasource.Resource.GetAppID()
	datasourceName := datasource.Resource.GetName()
	// 默认使用项目图标
	iconName := datasource.Resource.GetIconName()
	req.AppID = &appID
	req.DatasourceName = &datasourceName
	req.IconName = &iconName
	// 计算测试持续时间,以及测试时间线
	caseStartTime := req.GetCases()[0].GetQueryConfig().GetStartTime()
	caseEndTime := req.GetCases()[len(req.GetCases())-1].GetQueryConfig().GetEndTime()
	testDurationMill := caseEndTime - caseStartTime          // 查询的时间戳必须是毫秒级别
	testDurationStr := milliTimestampToStr(testDurationMill) // 转换为易读格式，如 "1h2m3s"
	testTimeline := fmt.Sprintf("%s ~ %s",
		time.UnixMilli(caseStartTime).Format("2006-01-02 15:04:05"),
		time.UnixMilli(caseEndTime).Format("2006-01-02 15:04:05"))

	req.Duration = &testDurationStr
	req.TestTimeline = &testTimeline
	createdReport, err := s.reportRepo.CreateReport(ctx, req)
	if err != nil {
		logger.Error("create report failed: %v", err)
		return baseV1.Failed(fmt.Errorf("创建报告失败: %v", err), int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}

	reportID := createdReport.Id

	// 3. 提交异步任务到任务池（设置回调）
	taskID := s.taskPool.Submit(
		"create_report",
		func(task *taskpool.Task) error {
			return s.processReport(context.Background(), createdReport, datasource, task)
		},
		taskpool.WithTaskName(fmt.Sprintf("生成报告: %s", req.GetName())),
		taskpool.WithTaskMetadata(map[string]any{
			"report_id":   reportID,
			"total_cases": len(req.GetCases()),
		}),
		// 完成回调：标记报告完成
		taskpool.WithOnComplete(func() {
			s.reportRepo.UpdateReportStatus(context.Background(), reportID, &reportV1.ReportStatus{
				Status: string(taskpool.TaskStatusCompleted),
			})
			logger.Info("report %s completed via callback", reportID)
		}),
		// 错误回调：标记报告失败
		taskpool.WithOnError(func(err error) {
			s.reportRepo.UpdateReportStatus(context.Background(), reportID, &reportV1.ReportStatus{
				Status:   string(taskpool.TaskStatusFailed),
				ErrorMsg: err.Error(),
			})
			logger.Error("report %s failed via callback: %v", reportID, err)
		}),
	)

	// 更新 report_status 中的 task_id
	createdReport.Resource.GetReportStatus().TaskID = taskID
	s.reportRepo.UpdateReportStatus(ctx, reportID, createdReport.Resource.GetReportStatus())

	logger.Info("report %s submitted as task %s", reportID, taskID)

	// 4. 立即返回
	return baseV1.Success(baseV1.WithData(createdReport))
}

// GetReportTask
// @route /apis/v1/report/task/get [POST]
func (s *ReportHandler) GetReportTask(ctx context.Context, req *baseV1.IdRequest) *baseV1.Response {
	reportID := req.GetID()

	// 1. 从数据库查询报告信息
	report, err := s.reportRepo.GetReport(ctx, reportID)
	if err != nil {
		return baseV1.Failed(fmt.Errorf("报告不存在: %v", err), int64(baseV1.BaseErrorCode_NOT_FOUND)) // NOT_FOUND
	}

	// 2. 返回 ReportStatus（已经包含了所有进度信息）
	reportStatus := report.Resource.GetReportStatus()
	if reportStatus == nil {
		return baseV1.Failed(fmt.Errorf("报告状态不存在"), int64(baseV1.BaseErrorCode_NOT_FOUND)) // NOT_FOUND
	}

	// 3. 如果任务仍在运行，从任务池获取实时进度
	taskInfo, exists := s.taskPool.GetTask(reportStatus.TaskID)
	if !exists {
		// 不存在，可能是已经从缓存中删除，如果报告状态已完成也要返回空的任务信息和任务状态，前端会始终显示已完成。
		if reportStatus.Status == string(taskpool.TaskStatusCompleted) {
			return baseV1.Success(baseV1.WithData(map[string]any{
				"report_status": reportStatus,
			}))
		}
		return baseV1.Failed(fmt.Errorf("报告中的任务不存在, 报告ID(%s) 任务ID(%s)", reportID, reportStatus.TaskID),
			int64(baseV1.BaseErrorCode_NOT_FOUND)) // NOT_FOUND
	}
	return baseV1.Success(baseV1.WithData(map[string]any{
		"report_status": reportStatus,
		"task_info":     taskInfo,
	}))
}

// GetReport
// @route /apis/v1/report/get [POST]
func (s *ReportHandler) GetReport(ctx context.Context, req *baseV1.IdRequest) *baseV1.Response {
	report, err := s.reportRepo.GetReport(ctx, req.GetID())
	if err != nil {
		return baseV1.Failed(fmt.Errorf("报告不存在: %v", err), int64(baseV1.BaseErrorCode_NOT_FOUND)) // NOT_FOUND
	}
	return baseV1.Success(baseV1.WithData(report))
}

// GetChunk
// @route /apis/v1/report/chunk/get [POST]
func (s *ReportHandler) GetChunk(ctx context.Context, req *baseV1.IdRequest) *baseV1.Response {
	data, err := s.getChunkData(ctx, req.GetID())
	if err != nil {
		return baseV1.Failed(err, int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	return baseV1.Success(baseV1.WithData(data))
}

// getChunkData 内部方法：获取单个 chunk 数据（优先缓存，缓存未命中则查 DB + 解压 + 缓存）
// 如果 chunk 是多分片的一部分，会自动查找并合并所有分片
func (s *ReportHandler) getChunkData(ctx context.Context, chunkID string) (chunkDataWithInfo, error) {
	// 1. 先从缓存查找
	if cachedData, ok := s.chunkCache.Get(chunkID); ok {
		logger.Debug("chunk %s hit cache", chunkID)
		return cachedData, nil
	}

	// 2. 缓存未命中，从数据库查询
	logger.Debug("chunk %s cache miss, querying from database", chunkID)
	chunk, err := s.reportRepo.GetChunk(ctx, chunkID)
	if err != nil {
		return chunkDataWithInfo{}, fmt.Errorf("chunk不存在: %v", err)
	}

	// 3. 检查是否为分片 chunk
	if chunk.Resource.IsSetTotalParts() && chunk.Resource.GetTotalParts() > 1 {
		// 分片场景：通过 report_id + stress_id 查找所有分片，按 part_index 排序合并
		return s.getMultiPartChunkData(ctx, chunk, chunkID)
	}

	// 4. 非分片：直接解压
	decompressedData, err := utils.Decompress(chunk.Resource.GetCompressedData())
	if err != nil {
		return chunkDataWithInfo{}, fmt.Errorf("解压数据失败: %v", err)
	}

	// 5. 反序列化为 chunkData
	var data chunkData
	if err := sonic.Unmarshal(decompressedData, &data); err != nil {
		return chunkDataWithInfo{}, fmt.Errorf("反序列化数据失败: %v", err)
	}
	result := chunkDataWithInfo{
		chunkData:    data,
		OriginalSize: chunk.Resource.GetOriginalSize(),
		PointCount:   chunk.Resource.GetPointCount(),
		MetricCount:  chunk.Resource.GetMetricCount(),
	}
	// 6. 更新缓存
	s.chunkCache.Put(chunkID, result)
	logger.Debug("chunk %s cached, original_size: %d bytes, point_count: %d, metric_count: %d",
		chunkID, result.OriginalSize, result.PointCount, result.MetricCount)

	return result, nil
}

// getMultiPartChunkData 处理分片 chunk 的合并读取
// 通过 report_id + stress_id 查找同一 case 的所有分片，按 part_index 排序后合并
func (s *ReportHandler) getMultiPartChunkData(ctx context.Context, firstChunk *repo.ChunkDocument, cacheKey string) (chunkDataWithInfo, error) {
	reportID := firstChunk.Resource.GetReportID()
	stressID := firstChunk.Resource.GetStressID()
	totalParts := int(firstChunk.Resource.GetTotalParts())

	logger.Info("loading multi-part chunk: report_id=%s, stress_id=%s, total_parts=%d", reportID, stressID, totalParts)

	// 查询同一 report_id + stress_id 的所有 chunk parts
	allPartsQuery := &baseV1.QueryRequest{
		Page:     1,
		PageSize: int64(totalParts + 5), // 留余量
		Query:    fmt.Sprintf(`{"report_id":"%s","stress_id":"%s","total_parts":{"$exists":true}}`, reportID, stressID),
	}
	chunkDocs, _, err := s.reportRepo.ListChunk(ctx, allPartsQuery)
	if err != nil {
		return chunkDataWithInfo{}, fmt.Errorf("查询分片 chunk 列表失败: %v", err)
	}
	if len(chunkDocs) < totalParts {
		return chunkDataWithInfo{}, fmt.Errorf("分片 chunk 不完整: 期望 %d 个, 找到 %d 个", totalParts, len(chunkDocs))
	}

	// 按 part_index 排序
	sortedParts := make([]*repo.ChunkDocument, totalParts)
	for _, doc := range chunkDocs {
		idx := int(doc.Resource.GetPartIndex())
		if idx >= 0 && idx < totalParts {
			sortedParts[idx] = doc
		}
	}

	// 拼接 compressed_data
	var allCompressedData []byte
	for i, part := range sortedParts {
		if part == nil {
			return chunkDataWithInfo{}, fmt.Errorf("分片 chunk 缺少 part %d", i)
		}
		allCompressedData = append(allCompressedData, part.Resource.GetCompressedData()...)
	}

	logger.Info("multi-part chunk assembled: %d bytes from %d parts", len(allCompressedData), totalParts)

	// 解压
	decompressedData, err := utils.Decompress(allCompressedData)
	if err != nil {
		return chunkDataWithInfo{}, fmt.Errorf("解压多分片数据失败: %v", err)
	}

	// 反序列化
	var data chunkData
	if err := sonic.Unmarshal(decompressedData, &data); err != nil {
		return chunkDataWithInfo{}, fmt.Errorf("反序列化多分片数据失败: %v", err)
	}

	result := chunkDataWithInfo{
		chunkData:    data,
		OriginalSize: firstChunk.Resource.GetOriginalSize(),
		PointCount:   firstChunk.Resource.GetPointCount(),
		MetricCount:  firstChunk.Resource.GetMetricCount(),
	}

	// 缓存
	s.chunkCache.Put(cacheKey, result)
	logger.Info("multi-part chunk cached (key=%s), original_size: %d bytes", cacheKey, result.OriginalSize)

	return result, nil
}

// getChunkDataByIDs 内部方法：获取 chunk 数据，支持多 chunk 分片合并
// 当 chunkIDs 只有一个元素时，等价于 getChunkData
// 当 chunkIDs 有多个元素时，按顺序拼接所有 part 的 compressed_data，然后解压
func (s *ReportHandler) getChunkDataByIDs(ctx context.Context, chunkIDs []string) (chunkDataWithInfo, error) {
	if len(chunkIDs) == 0 {
		return chunkDataWithInfo{}, fmt.Errorf("chunk IDs 为空")
	}

	// 优先从缓存查找（用首个 ID 作为缓存 key）
	cacheKey := chunkIDs[0]
	if cachedData, ok := s.chunkCache.Get(cacheKey); ok {
		logger.Debug("chunk %s hit cache (multi-part key)", cacheKey)
		return cachedData, nil
	}

	// 单个 chunk 直接走简单路径
	if len(chunkIDs) == 1 {
		return s.getChunkData(ctx, chunkIDs[0])
	}

	// 多个 chunk：按顺序读取并拼接 compressed_data
	logger.Info("loading multi-part chunk: %d parts", len(chunkIDs))
	var allCompressedData []byte
	var originalSize int64
	var pointCount int32
	var metricCount int32

	for i, chunkID := range chunkIDs {
		chunk, err := s.reportRepo.GetChunk(ctx, chunkID)
		if err != nil {
			return chunkDataWithInfo{}, fmt.Errorf("获取 chunk part %d/%d 失败 (id=%s): %v", i+1, len(chunkIDs), chunkID, err)
		}
		allCompressedData = append(allCompressedData, chunk.Resource.GetCompressedData()...)
		// 取第一个 part 的元数据（所有 part 的元数据相同）
		if i == 0 {
			originalSize = chunk.Resource.GetOriginalSize()
			pointCount = chunk.Resource.GetPointCount()
			metricCount = chunk.Resource.GetMetricCount()
		}
	}

	logger.Info("multi-part chunk assembled: %d bytes from %d parts", len(allCompressedData), len(chunkIDs))

	// 解压拼接后的数据
	decompressedData, err := utils.Decompress(allCompressedData)
	if err != nil {
		return chunkDataWithInfo{}, fmt.Errorf("解压多分片数据失败: %v", err)
	}

	// 反序列化
	var data chunkData
	if err := sonic.Unmarshal(decompressedData, &data); err != nil {
		return chunkDataWithInfo{}, fmt.Errorf("反序列化多分片数据失败: %v", err)
	}

	result := chunkDataWithInfo{
		chunkData:    data,
		OriginalSize: originalSize,
		PointCount:   pointCount,
		MetricCount:  metricCount,
	}

	// 缓存（用首个 ID 作为 key）
	s.chunkCache.Put(cacheKey, result)
	logger.Info("multi-part chunk cached (key=%s), original_size: %d bytes", cacheKey, originalSize)

	return result, nil
}

// GetReportChunkList
// @route /apis/v1/report/chunk/list [POST]
func (s *ReportHandler) GetReportChunkList(ctx context.Context, req *baseV1.IdRequest) *baseV1.Response {
	reportID := req.GetID()

	// 1. 获取报告
	report, err := s.reportRepo.GetReport(ctx, reportID)
	if err != nil {
		return baseV1.Failed(fmt.Errorf("报告不存在: %v", err), int64(baseV1.BaseErrorCode_NOT_FOUND))
	}

	cases := report.Resource.GetCases()
	if len(cases) == 0 {
		return baseV1.Failed(fmt.Errorf("报告没有用例和数据"), int64(baseV1.BaseErrorCode_NOT_FOUND))
	}

	// 2. 遍历 cases，逐个调用 getChunkDataByIDs 获取数据（自动处理缓存和分片合并）
	chunkDataList := make([]chunkDataWithInfo, 0, len(cases))
	for _, singleCase := range cases {
		chunkIDs := getCaseChunkIDs(singleCase)
		if len(chunkIDs) == 0 {
			continue
		}

		// 调用内部方法获取数据（支持分片合并）
		data, err := s.getChunkDataByIDs(ctx, chunkIDs)
		if err != nil {
			return baseV1.Failed(fmt.Errorf("获取 chunk 数据失败 (chunk_ids=%v): %v", chunkIDs, err), int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
		}

		chunkDataList = append(chunkDataList, data)
	}

	return baseV1.Success(baseV1.WithData(chunkDataList))
}

// ListReport
// @route /apis/v1/report/list [POST]
func (s *ReportHandler) ListReport(ctx context.Context, req *baseV1.QueryRequest) *baseV1.Response {
	reports, page, err := s.reportRepo.ListReport(ctx, req)
	if err != nil {
		return baseV1.Failed(fmt.Errorf("报告列表查询失败: %v", err), int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	return baseV1.Success(baseV1.WithData(reports), baseV1.WithPage(page))
}

// DeleteReport
// @route /apis/v1/report/del [POST]
func (s *ReportHandler) DeleteReport(ctx context.Context, req *baseV1.IdRequest) *baseV1.Response {
	err := s.reportRepo.DeleteReport(ctx, req.GetID())
	if err != nil {
		return baseV1.Failed(fmt.Errorf("报告删除失败: %v", err), int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	return baseV1.Success()
}

// ProgressInfo 进度信息
type ProgressInfo struct {
	Progress  int32  // 进度百分比 (0-100)
	CaseStr   string // case 进度字符串，如 "1/3"
	FilterStr string // filter 进度字符串，如 "2/5"
	WindowStr string // window 进度字符串，如 "3/10"
}

// progressCallback 进度回调函数类型
type progressCallback func(info ProgressInfo)

// processReport 处理报告生成（任务池执行函数）
func (s *ReportHandler) processReport(
	ctx context.Context,
	report *repo.ReportDocument,
	datasource *repo.DatasourceDocument,
	task *taskpool.Task,
) error {
	reportID := report.Id
	cases := report.Resource.GetCases()
	totalCases := len(cases)

	// 创建 map 用于收集所有指标名称（去重）
	metricNamesMap := make(map[string]bool)

	logger.Info("start processing report %s with %d cases", reportID, totalCases)
	for i, singleCase := range cases {
		// 检查任务是否被取消
		select {
		case <-task.CancelChan():
			logger.Warn("report %s generation cancelled", reportID)
			return fmt.Errorf("report generation cancelled")
		default:
		}
		// 计算当前 case 的进度范围
		// 例如：3 个 case，第 1 个 case 的范围是 [0, 33]，第 2 个是 [33, 66]，第 3 个是 [66, 100]
		caseProgressStart := int32(i * 100 / totalCases)
		caseProgressEnd := int32((i + 1) * 100 / totalCases)

		// 创建进度回调，将 case 内的进度 [0-100] 映射到全局进度范围
		// 使用闭包局部变量记录上次日志时间，避免并发问题
		var lastProgressLogTime time.Time
		const progressLogCooldown = time.Second

		onProgress := func(info ProgressInfo) {
			// info.Progress 是 case 内部的进度 (0-100)
			// 映射到全局进度: start + (end - start) * progress / 100
			globalProgress := caseProgressStart + (caseProgressEnd-caseProgressStart)*info.Progress/100

			// 构建进度日志字符串
			groupStr := ""
			if info.CaseStr != "" {
				groupStr += fmt.Sprintf("case(%s)", info.CaseStr)
			}
			if info.FilterStr != "" {
				groupStr += fmt.Sprintf(" filter(%s)", info.FilterStr)
			}
			if info.WindowStr != "" {
				groupStr += fmt.Sprintf(" window(%s)", info.WindowStr)
			}

			// 输出日志（控制频率）
			now := time.Now()
			if groupStr != "" {
				// 详细进度（降频输出）
				if lastProgressLogTime.IsZero() || now.Sub(lastProgressLogTime) >= progressLogCooldown {
					logger.Debug("report %s %s progress: %d%%", reportID, groupStr, globalProgress)
					lastProgressLogTime = now
				}
			} else {
				// 阶段性进度（正常输出）
				logger.Info("report %s progress: %d%%", reportID, globalProgress)
			}

			task.UpdateProgress(globalProgress)
		}

		// 处理单个用例，传递进度回调和指标名称收集器
		chunkIDs, err := s.processSingleCase(ctx, reportID, singleCase, datasource, onProgress, fmt.Sprintf("%d/%d", i+1, totalCases), metricNamesMap)
		if err != nil {
			return fmt.Errorf("process case %s failed: %w", singleCase.GetStressID(), err)
		}
		setCaseChunkIDs(singleCase, chunkIDs)
		// 确保 case 完成后进度到达预期值
		task.UpdateProgress(caseProgressEnd)
	}

	// 将收集到的指标名称转换为数组并排序，保存到报告中
	if len(metricNamesMap) > 0 {
		metricNames := make([]string, 0, len(metricNamesMap))
		for name := range metricNamesMap {
			metricNames = append(metricNames, name)
		}

		// 字典序排序
		for i := 0; i < len(metricNames); i++ {
			for j := i + 1; j < len(metricNames); j++ {
				if metricNames[i] > metricNames[j] {
					metricNames[i], metricNames[j] = metricNames[j], metricNames[i]
				}
			}
		}

		if report.Resource.MetricInfo == nil {
			report.Resource.MetricInfo = &reportV1.MetricInfo{}
		}
		report.Resource.MetricInfo.MetricNameList = metricNames

		logger.Info("收集到 %d 个指标名称: %v", len(metricNames), metricNames)
	}

	//
	logger.Info("report %s processing finished", reportID)
	s.reportRepo.UpdateReportDocument(ctx, report)
	return nil
}

// processSingleCase 处理单个测试用例
// onProgress: 进度回调函数，参数为 case 内部进度 (0-100)
// metricNamesMap: 用于收集指标名称的 map（去重）
// 返回 chunk IDs 列表（大数据时会分片为多个 chunk）
func (s *ReportHandler) processSingleCase(
	ctx context.Context,
	reportID string,
	singleCase *reportV1.SingleCase,
	datasource *repo.DatasourceDocument,
	onProgress progressCallback,
	caseProgressStr string,
	metricNamesMap map[string]bool,
) ( /* chunkIDs */ []string, error) {
	queryConfig := singleCase.GetQueryConfig()
	stressID := singleCase.GetStressID()

	// Case 内部进度分配：查询占 70%，聚合占 20%，存储占 10%
	const (
		queryWeight     = 70
		aggregateWeight = 20
		// saveWeight   = 10  // 存储很快，不单独显示进度
	)

	// 1. 从 Pushgateway 查询原始数据（贪婪模式）
	// 查询进度从 0 到 queryWeight (70%)
	queryProgress := func(info ProgressInfo) {
		if onProgress != nil {
			info.Progress = info.Progress * queryWeight / 100
			onProgress(info)
		}
	}
	rawPoints, err := s.queryRawDataFromPushgateway(ctx, queryConfig, datasource, queryProgress, caseProgressStr)
	if err != nil {
		return nil, fmt.Errorf("query raw data failed: %w", err)
	}

	if len(rawPoints) == 0 {
		logger.Warn("stress_id %s, case %s: no data found", stressID, singleCase.GetName())
		// 即使没有数据也创建空chunk
	}

	logger.Info("stress_id %s, case %s: fetched %d raw data points from pushgateway", stressID, singleCase.GetName(), len(rawPoints))

	// 2. 重新聚合数据（按指定间隔）
	// 聚合进度从 queryWeight 到 queryWeight + aggregateWeight (70% - 90%)
	if onProgress != nil {
		onProgress(ProgressInfo{Progress: queryWeight}) // 查询完成，进度 70%
	}
	// 聚合进度回调：将聚合窗口进度 [0-100] 映射到 [70-90]
	aggregateProgress := func(windowProgress int32) {
		if onProgress != nil {
			progress := queryWeight + windowProgress*aggregateWeight/100
			onProgress(ProgressInfo{Progress: progress, CaseStr: caseProgressStr})
		}
	}
	aggregatedData, tables, err := s.reaggregateData(rawPoints, queryConfig, datasource, aggregateProgress)
	if err != nil {
		return nil, fmt.Errorf("reaggregate data failed: %w", err)
	}
	if onProgress != nil {
		onProgress(ProgressInfo{Progress: queryWeight + aggregateWeight}) // 聚合完成，进度 90%
	}

	logger.Info("stress_id %s, case %s: aggregated to %d metrics, %d points", stressID, singleCase.GetName(),
		dataprocess.CountMetrics(aggregatedData), dataprocess.CountPoints(aggregatedData))

	chunkData := chunkData{
		Tables: tables,
		Points: aggregatedData,
	}
	chunkData.Tables = tables
	chunkData.Points = aggregatedData

	// 收集指标名称（在生成时顺便收集，避免后续重复查询）
	// 注意：aggregatedData.K 的格式是 [metric_name, labels, metric_name, labels, ...]
	// 所以只收集偶数索引位置的元素（指标名称），跳过奇数索引位置的 labels
	if metricNamesMap != nil && aggregatedData != nil && len(aggregatedData.K) > 0 {
		for i := 0; i < len(aggregatedData.K); i += 2 {
			metricName := aggregatedData.K[i]
			// 过滤掉 labels 格式的字符串（以 "{" 开头）
			if !strings.HasPrefix(metricName, "{") {
				metricNamesMap[metricName] = true
			}
		}
	}

	// 2.5 计算 rate 统计（如果配置了 rate_metrics）
	// rate 计算基于已聚合的数据，不影响 chunk 存储，结果直接存储到 SingleCase
	if rateMetrics := queryConfig.GetRateMetrics(); len(rateMetrics) > 0 {
		rateStatistics := dataprocess.CalculateCaseRateStatistics(
			singleCase.GetName(),
			aggregatedData,
			rateMetrics,
			queryConfig.GetStartTime(),
			queryConfig.GetEndTime(),
		)
		if rateStatistics != nil {
			singleCase.RateStatistics = rateStatistics
			logger.Info("stress_id %s, case %s: calculated rate statistics for %d metrics",
				stressID, singleCase.GetName(), len(rateStatistics.Statistics))
		}
	}

	// 3. 序列化 + 压缩数据
	jsonData, err := sonic.Marshal(chunkData)
	if err != nil {
		return nil, fmt.Errorf("marshal data failed: %w", err)
	}

	compressedData, err := utils.CompressWithLevel(jsonData, 7) // 使用较高压缩率
	if err != nil {
		return nil, fmt.Errorf("compress data failed: %w", err)
	}

	logger.Info("stress_id %s, case %s: compressed %d bytes -> %d bytes (ratio: %.2f%%)", stressID, singleCase.GetName(),
		len(jsonData), len(compressedData),
		float64(len(compressedData))/float64(len(jsonData))*100)

	pointCount := int32(dataprocess.CountPoints(aggregatedData))
	metricCount := int32(dataprocess.CountMetrics(aggregatedData))
	originalSize := int64(len(jsonData))

	// 4. 存储 chunk（支持大数据自动分片）
	var chunkIDs []string

	if len(compressedData) <= maxChunkPartSize {
		// 数据未超过阈值，直接存储为单个 chunk（不设置分片字段，兼容旧逻辑）
		chunk := &reportV1.Chunk{
			ReportID:       reportID,
			StressID:       stressID,
			CompressedData: compressedData,
			OriginalSize:   originalSize,
			PointCount:     pointCount,
			MetricCount:    metricCount,
		}
		chunkDoc, err := s.reportRepo.CreateChunk(ctx, chunk)
		if err != nil {
			return nil, fmt.Errorf("create chunk failed: %w", err)
		}
		chunkIDs = []string{chunkDoc.Id}

		// 将压缩前的数据存储到缓存
		s.chunkCache.Put(chunkDoc.Id, chunkDataWithInfo{
			chunkData:    chunkData,
			OriginalSize: originalSize,
			PointCount:   pointCount,
			MetricCount:  metricCount,
		})
	} else {
		// 数据超过阈值，按固定大小切分为多个 chunk parts
		totalParts := (len(compressedData) + maxChunkPartSize - 1) / maxChunkPartSize
		logger.Info("stress_id %s, case %s: compressed data %d bytes exceeds %d limit, splitting into %d parts",
			stressID, singleCase.GetName(), len(compressedData), maxChunkPartSize, totalParts)

		totalPartsI32 := int32(totalParts)
		for partIdx := 0; partIdx < totalParts; partIdx++ {
			start := partIdx * maxChunkPartSize
			end := start + maxChunkPartSize
			if end > len(compressedData) {
				end = len(compressedData)
			}
			partData := compressedData[start:end]
			partIdxI32 := int32(partIdx)

			chunk := &reportV1.Chunk{
				ReportID:       reportID,
				StressID:       stressID,
				CompressedData: partData,
				OriginalSize:   originalSize,
				PointCount:     pointCount,
				MetricCount:    metricCount,
				PartIndex:      &partIdxI32,
				TotalParts:     &totalPartsI32,
			}
			chunkDoc, err := s.reportRepo.CreateChunk(ctx, chunk)
			if err != nil {
				return nil, fmt.Errorf("create chunk part %d/%d failed: %w", partIdx+1, totalParts, err)
			}
			chunkIDs = append(chunkIDs, chunkDoc.Id)
			logger.Info("stress_id %s, case %s: chunk part %d/%d saved (%d bytes)",
				stressID, singleCase.GetName(), partIdx+1, totalParts, len(partData))
		}

		// 分片场景：用首个 chunkID 作为缓存 key（getChunkData 会用它来查找）
		s.chunkCache.Put(chunkIDs[0], chunkDataWithInfo{
			chunkData:    chunkData,
			OriginalSize: originalSize,
			PointCount:   pointCount,
			MetricCount:  metricCount,
		})
	}

	if onProgress != nil {
		onProgress(ProgressInfo{Progress: 100}) // 存储完成，进度 100%
	}

	logger.Info("stress_id %s, case %s: chunk saved successfully (%d parts)", stressID, singleCase.GetName(), len(chunkIDs))
	return chunkIDs, nil
}

// queryRawDataFromPushgateway 从 Pushgateway 查询原始数据（贪婪模式）
// onProgress: 查询进度回调，参数为查询进度 (0-100)
func (s *ReportHandler) queryRawDataFromPushgateway(
	ctx context.Context,
	config *reportV1.QueryConfig,
	datasource *repo.DatasourceDocument,
	onProgress progressCallback,
	caseProgressStr string,
) ([]pkgaggregator.RawMetricPoint, error) {
	// 1. 获取数据源配置
	pgAddrs := datasource.Resource.GetPushgatewayAddrList()
	appID := datasource.Resource.GetAppID()
	filters := config.GetFilters()

	if len(pgAddrs) == 0 {
		return nil, fmt.Errorf("no pushgateway address configured for datasource %s", datasource.Id)
	}

	// 预计算时间窗口数量，用于进度计算
	windows := createTimeWindows(config.GetStartTime(), config.GetEndTime(), 10*time.Minute, false) // 查询不对齐边界
	totalWindows := len(windows)
	totalFilters := len(filters)
	// 总任务数 = filters * windows（最坏情况）
	totalTasks := totalFilters * totalWindows
	completedTasks := 0

	logger.Info("querying pushgateway (greedy mode): %d addresses, %d filters, %d windows per filter",
		len(pgAddrs), totalFilters, totalWindows)

	// 2. 为每个 Filter 维护"已找到"标记
	filterFound := make([]bool, totalFilters)
	allPoints := make([]pkgaggregator.RawMetricPoint, 0)

	// 3. 遍历所有 Pushgateway（贪婪查询）
	for pgIdx, pgAddr := range pgAddrs {
		logger.Debug("querying pushgateway [%d/%d]: %s", pgIdx+1, len(pgAddrs), pgAddr)

		// 检查是否所有 Filter 都已找到
		allFound := true
		for _, found := range filterFound {
			if !found {
				allFound = false
				break
			}
		}
		if allFound {
			logger.Info("all filters found, stop querying remaining pushgateways")
			break
		}

		// 4. 查询未找到数据的 Filter
		for filterIdx, filter := range filters {
			filterProgressStr := fmt.Sprintf("%d/%d", filterIdx+1, totalFilters)
			if filterFound[filterIdx] {
				continue // 跳过已找到的
			}
			// 这里要根据时间范围进行分段, 最大窗口为10分钟
			for windowIdx, window := range windows {
				windowProgressStr := fmt.Sprintf("%d/%d", windowIdx+1, totalWindows)
				query := &pushgatewayV1.MetricQuery{
					AppID:     appID,
					StartTime: window.startTime,
					EndTime:   window.endTime,
				}

				// 设置可选的指标名称和标签
				if filter.IsSetName() {
					query.MetricName = stringPtr(filter.GetName())
				}
				if filter.IsSetLabels() {
					query.Labels = filter.GetLabels()
				}
				rawPoints, err := s.collector.QueryRangeMetricsByPushgateway(ctx, pgAddr, datasource.Id, query)
				if err != nil {
					logger.Warn("filter_idx(%d) query failed in %s: %v", filterIdx, pgAddr, err)
					continue
				}
				// 解析数据
				if len(rawPoints) == 0 {
					logger.Warn("filter_idx(%d) empty response data in %s", filterIdx, pgAddr)
					// 即使没有数据也更新进度
					completedTasks++
					if onProgress != nil && totalTasks > 0 {
						onProgress(ProgressInfo{
							Progress:  int32(completedTasks * 100 / totalTasks),
							CaseStr:   caseProgressStr,
							FilterStr: filterProgressStr,
							WindowStr: windowProgressStr,
						})
					}
					continue
				}

				// 找到数据！
				filterFound[filterIdx] = true
				allPoints = append(allPoints, rawPoints...)

				// 更新进度：已完成当前 filter 的所有窗口
				completedTasks++
				if onProgress != nil && totalTasks > 0 {
					onProgress(ProgressInfo{
						Progress:  int32(completedTasks * 100 / totalTasks),
						CaseStr:   caseProgressStr,
						FilterStr: filterProgressStr,
						WindowStr: windowProgressStr,
					})
				}

				time.Sleep(100 * time.Millisecond)
			}
		}
	}

	// 5. 检查未找到的 Filter
	notFound := []int{}
	for idx, found := range filterFound {
		if !found {
			notFound = append(notFound, idx)
		}
	}
	if len(notFound) > 0 {
		logger.Warn("filters %v not found in any pushgateway", notFound)
	}

	logger.Info("greedy query completed: %d points from %d/%d filters",
		len(allPoints), len(filters)-len(notFound), len(filters))

	return allPoints, nil
}

// reaggregateData 重新聚合数据（按指定间隔）
// onProgress: 聚合进度回调，参数为聚合窗口进度 (0-100)
func (s *ReportHandler) reaggregateData(
	rawPoints []pkgaggregator.RawMetricPoint,
	config *reportV1.QueryConfig,
	datasource *repo.DatasourceDocument,
	onProgress func(int32),
) (*dataprocess.PointsResponse, []*dataprocess.SummaryTable, error) {
	if len(rawPoints) == 0 {
		return &dataprocess.PointsResponse{
			K: []string{},
			V: [][][]dataprocess.RawData{},
		}, nil, nil
	}

	// 解析聚合间隔
	interval, err := time.ParseDuration(config.GetAggregationInterval())
	if err != nil {
		return nil, nil, fmt.Errorf("invalid aggregation interval: %s", config.GetAggregationInterval())
	}

	// all aggregated points
	allAggregatedPoints := make([]pkgaggregator.AggregatedPoint, 0)
	// 创建时间窗口
	windows := createTimeWindows(config.GetStartTime(), config.GetEndTime(), interval, true) // 聚合需要对齐边界
	totalWindows := len(windows)

	for i, window := range windows {
		// 筛选窗口内的数据点
		windowPoints := filterPointsInWindow(rawPoints, window.startTime, window.endTime)
		// 聚合计算
		aggregated := pkgaggregator.AggregateRaw(windowPoints, config.GetAggregationInterval(), time.Unix(window.startTime/1000, 0))
		allAggregatedPoints = append(allAggregatedPoints, aggregated...)

		// 更新进度
		if onProgress != nil && totalWindows > 0 {
			windowProgress := int32((i + 1) * 100 / totalWindows)
			onProgress(windowProgress)
		}

		time.Sleep(100 * time.Millisecond) // 因为是后台任务，允许降频
	}

	compressedData := dataprocess.BuildCompressedData(allAggregatedPoints)
	// 4. 生成汇总表格
	metricConfigMap := dataprocess.BuildMetricConfigMap(datasource.Resource.GetGroupmap())
	tables := dataprocess.GenerateMultipleTables(compressedData, datasource.Resource.GetSummaryConfig(), metricConfigMap)
	return compressedData, tables, nil
}

// createTimeWindows 创建时间窗口列表
// alignToBoundary: 是否对齐到边界
//   - true:  聚合操作时使用，对齐到 interval 边界（如 10:00, 10:15, 10:30...）
//   - false: 查询操作时使用，严格从 startTime 开始分段
func createTimeWindows(startTime, endTime int64, interval time.Duration, alignToBoundary bool) []timeWindow {
	windows := make([]timeWindow, 0)
	intervalMillis := interval.Milliseconds()

	// 确定起始点
	var current int64
	if alignToBoundary {
		// 对齐到窗口边界（向下取整）
		current = (startTime / intervalMillis) * intervalMillis
	} else {
		// 严格从 startTime 开始
		current = startTime
	}

	for current < endTime {
		windowEnd := current + intervalMillis
		if windowEnd > endTime {
			windowEnd = endTime
		}
		windows = append(windows, timeWindow{
			startTime: current,
			endTime:   windowEnd,
		})
		current += intervalMillis
	}

	return windows
}

// filterPointsInWindow 筛选时间窗口内的数据点
func filterPointsInWindow(points []pkgaggregator.RawMetricPoint, startTime, endTime int64) []pkgaggregator.RawMetricPoint {
	filtered := make([]pkgaggregator.RawMetricPoint, 0)
	startSec := startTime
	endSec := endTime

	for _, point := range points {
		t := point.Timestamp
		if t >= startSec && t < endSec {
			filtered = append(filtered, point)
		}
	}
	// 输出一下过滤后的数据点，调试用，统计指标名称数量，唯一labels数量。
	metricsMap := make(map[string]int) // key: name
	pointsMap := make(map[string]int)  // key: name|labels
	for _, point := range filtered {
		metricsMap[point.Name]++
		pointsMap[point.Name+"|"+point.Labels.String()]++
	}
	// logger.Debug("filterPointsInWindow: %d metrics, %d points", len(metricsMap), len(pointsMap))
	return filtered
}

// stringPtr 辅助函数：字符串指针
func stringPtr(s string) *string {
	return &s
}

// milliTimestampToStr 将毫秒持续时间转换为易读的时间格式
// 例如：61223 毫秒 -> "1m1s"
// 使用 Go 标准库 time.Duration 的格式化能力
func milliTimestampToStr(milliseconds int64) string {
	if milliseconds <= 0 {
		return "0s"
	}

	// 将毫秒转换为 time.Duration
	duration := time.Duration(milliseconds) * time.Millisecond

	// 精确到秒，忽略毫秒部分
	duration = duration.Round(time.Second)

	// 使用标准库的格式化（自动输出如 "1h2m3s", "5m30s", "1m1s" 等格式）
	return duration.String()
}

// UpdateReport
// @route /apis/v1/report/update [POST]
func (s *ReportHandler) UpdateReport(ctx context.Context, req *reportV1.UpdateReportRequest) *baseV1.Response {
	reportDoc, err := s.reportRepo.UpdateReportInfo(ctx, req.GetID(), req.GetReport())
	if err != nil {
		return baseV1.Failed(fmt.Errorf("更新报告失败: %v", err), int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	return baseV1.Success(baseV1.WithData(reportDoc))
}

// UploadIcon
// @route /apis/v1/report/icon/upload [POST]
func (s *ReportHandler) UploadIcon(ctx context.Context, req *reportV1.UploadIconRequest) *baseV1.Response {
	// 1. 验证数据源是否存在
	doc, err := s.reportRepo.GetReport(ctx, req.GetReportID())
	if err != nil {
		return baseV1.Failed(err, int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	if doc == nil {
		return baseV1.Failed(
			fmt.Errorf("report(%v) not found", req.GetReportID()),
			int64(baseV1.BaseErrorCode_NOT_FOUND),
		)
	}

	// 2. 验证文件扩展名（只允许 png/svg/jpg/jpeg）
	ext := strings.ToLower(filepath.Ext(req.FileName))
	allowedExts := map[string]bool{".png": true, ".svg": true, ".jpg": true, ".jpeg": true}
	if !allowedExts[ext] {
		return baseV1.Failed(
			fmt.Errorf("不支持的文件格式: %s, 仅支持 png/svg/jpg/jpeg", ext),
			int64(baseV1.BaseErrorCode_INVALID_PARAM),
		)
	}

	// 3. 验证文件魔数（防止伪造扩展名的恶意文件）
	if !validateImageMagicNumber(req.IconData, ext) {
		return baseV1.Failed(
			fmt.Errorf("文件内容与扩展名不匹配，可能存在安全风险"),
			int64(baseV1.BaseErrorCode_INVALID_PARAM),
		)
	}

	// 4. 清理文件名（防止路径注入）
	safeFileName := sanitizeFileName(req.FileName)
	if safeFileName == "" {
		return baseV1.Failed(
			fmt.Errorf("无效的文件名"),
			int64(baseV1.BaseErrorCode_INVALID_PARAM),
		)
	}

	// 5. 获取可执行文件所在目录，创建 icon/{数据源ID}/ 目录
	execPath, err := os.Executable()
	if err != nil {
		return baseV1.Failed(
			fmt.Errorf("获取可执行文件路径失败: %w", err),
			int64(baseV1.BaseErrorCode_INTERNAL_ERROR),
		)
	}
	execDir := filepath.Dir(execPath)
	iconDir := filepath.Join(execDir, "icon", req.GetReportID())

	// 创建目录（如果不存在）
	if err := os.MkdirAll(iconDir, 0755); err != nil {
		return baseV1.Failed(
			fmt.Errorf("创建图标目录失败: %w", err),
			int64(baseV1.BaseErrorCode_INTERNAL_ERROR),
		)
	}

	// 6. 保存文件
	iconPath := filepath.Join(iconDir, safeFileName)
	if err := os.WriteFile(iconPath, req.IconData, 0644); err != nil {
		return baseV1.Failed(
			fmt.Errorf("保存图标文件失败: %w", err),
			int64(baseV1.BaseErrorCode_INTERNAL_ERROR),
		)
	}

	// 7. 更新数据库中的 icon_name
	updatedDoc, err := s.reportRepo.UpdateReportIconName(ctx, req.GetReportID(), safeFileName)
	if err != nil {
		// 如果数据库更新失败，删除已保存的文件
		os.Remove(iconPath)
		return baseV1.Failed(
			fmt.Errorf("更新数据库失败: %w", err),
			int64(baseV1.BaseErrorCode_INTERNAL_ERROR),
		)
	}

	logger.Info("UploadIcon: report_id=%s, icon_name=%s, saved_path=%s",
		req.GetReportID(), safeFileName, iconPath)

	return baseV1.Success(baseV1.WithData(updatedDoc))
}

// validateImageMagicNumber 验证图片文件的魔数（文件头）
// 防止用户上传伪装成图片的恶意文件
func validateImageMagicNumber(data []byte, ext string) bool {
	if len(data) < 8 {
		return false
	}

	switch ext {
	case ".png":
		// PNG 魔数: 89 50 4E 47 0D 0A 1A 0A
		pngMagic := []byte{0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A}
		return bytes.HasPrefix(data, pngMagic)
	case ".jpg", ".jpeg":
		// JPEG 魔数: FF D8 FF
		jpegMagic := []byte{0xFF, 0xD8, 0xFF}
		return bytes.HasPrefix(data, jpegMagic)
	case ".svg":
		// SVG 是 XML 文本格式，检查是否以 <?xml 或 <svg 开头
		// 去除可能的 BOM 头
		content := bytes.TrimLeft(data, "\xef\xbb\xbf") // UTF-8 BOM
		contentStr := strings.TrimSpace(string(content[:min(len(content), 1024)]))
		return strings.HasPrefix(contentStr, "<?xml") ||
			strings.HasPrefix(contentStr, "<svg") ||
			strings.HasPrefix(contentStr, "<!DOCTYPE svg")
	default:
		return false
	}
}

// sanitizeFileName 清理文件名，防止路径遍历攻击
func sanitizeFileName(fileName string) string {
	// 只保留文件名部分（去除路径）
	fileName = filepath.Base(fileName)

	// 只允许字母、数字、下划线、连字符、点
	reg := regexp.MustCompile(`[^a-zA-Z0-9_\-.]`)
	fileName = reg.ReplaceAllString(fileName, "_")

	// 防止 .. 和 空文件名
	if fileName == "" || fileName == "." || fileName == ".." {
		return ""
	}

	// 限制文件名长度
	if len(fileName) > 100 {
		ext := filepath.Ext(fileName)
		name := strings.TrimSuffix(fileName, ext)
		if len(name) > 100-len(ext) {
			name = name[:100-len(ext)]
		}
		fileName = name + ext
	}

	return fileName
}

// CalculateReportScore
// @route /apis/v1/report/score/calculate [POST]
func (s *ReportHandler) CalculateReportScore(ctx context.Context, req *baseV1.IdRequest) *baseV1.Response {
	// 1. 参数校验
	reportID := req.GetID()
	if reportID == "" {
		return baseV1.Failed(fmt.Errorf("报告ID不能为空"), 1001)
	}

	// 2. 获取报告
	reportEntity, err := s.reportRepo.GetReport(ctx, reportID)
	if err != nil {
		logger.Error("获取报告失败: %v %v", err, reportID)
		return baseV1.Failed(fmt.Errorf("获取报告失败: %w", err), 1002)
	}

	report := reportEntity.Resource
	if report == nil {
		return baseV1.Failed(fmt.Errorf("报告数据为空"), 1002)
	}

	// 3. 检查评分配置
	if report.ScoringConfig == nil {
		return baseV1.Failed(fmt.Errorf("报告未配置评分标准"), 1001)
	}

	if report.ScoringConfig.DefaultConfig == nil || len(report.ScoringConfig.DefaultConfig.MetricConfigs) == 0 {
		return baseV1.Failed(fmt.Errorf("评分配置不完整：缺少默认配置或指标配置"), 1001)
	}

	// 4. 加载所有用例的汇总表格数据
	cases := report.GetCases()
	if len(cases) == 0 {
		return baseV1.Failed(fmt.Errorf("报告没有任何用例"), 1001)
	}

	caseScores := make([]*reportV1.CaseScore, 0, len(cases))

	for _, singleCase := range cases {
		// 获取该用例的 chunk IDs
		chunkIDs := getCaseChunkIDs(singleCase)
		if len(chunkIDs) == 0 {
			logger.Warn("用例没有chunk_id，跳过评分 case_name: %s", singleCase.GetName())
			continue
		}

		// 加载 chunk 数据
		chunkData, err := s.getChunkDataByIDs(ctx, chunkIDs)
		if err != nil {
			logger.Error("加载用例chunk数据失败 case_name: %s, chunk_ids: %v, error: %v", singleCase.GetName(), chunkIDs, err)
			continue
		}

		// 转换为 thrift 格式的 SummaryTable
		thriftTables := make([]*pointsV1.SummaryTable, len(chunkData.Tables))
		for i, table := range chunkData.Tables {
			thriftTables[i] = &pointsV1.SummaryTable{
				Name:  table.Name,
				Table: table.Table,
			}
		}

		// 获取该用例的评分配置（优先使用特定配置，否则使用默认配置）
		caseConfig := s.getCaseConfigForCase(report.ScoringConfig, singleCase.GetName())

		// 计算用例得分（传入 Rate 统计数据用于评分）
		caseScore, err := scoring.CalculateCaseScore(thriftTables, caseConfig, singleCase.GetName(), singleCase.RateStatistics)
		if err != nil {
			logger.Error("计算用例得分失败 case_name: %s, error: %v", singleCase.GetName(), err)
			continue
		}

		caseScores = append(caseScores, caseScore)
	}

	// 5. 检查是否有有效的用例得分
	if len(caseScores) == 0 {
		return baseV1.Failed(fmt.Errorf("没有任何用例成功计算得分"), 1002)
	}

	// 6. 计算报告总分
	reportScore := scoring.CalculateReportScore(caseScores)

	// 7. 更新报告的评分结果
	report.ReportScore = reportScore

	// 8. 保存到数据库
	reportEntity.Resource = report
	if _, err := s.reportRepo.UpdateReportDocument(ctx, reportEntity); err != nil {
		logger.Error("保存报告评分失败", "report_id", reportID, "error", err)
		return baseV1.Failed(fmt.Errorf("保存报告评分失败: %w", err), 1002)
	}

	logger.Info("报告评分计算完成",
		"report_id", reportID,
		"total_score", reportScore.TotalScore,
		"level", reportScore.Level,
		"case_count", len(caseScores))

	// 9. 返回评分结果
	return baseV1.Success(baseV1.WithData(reportScore))
}

// getCaseConfigForCase 获取指定用例的评分配置
// 优先使用特定用例配置，否则使用默认配置
func (s *ReportHandler) getCaseConfigForCase(scoringConfig *reportV1.ReportScoringConfig, caseName string) *reportV1.CaseScoringConfig {
	// 检查是否有特定用例的配置
	if scoringConfig.CaseConfigs != nil {
		for _, caseConfig := range scoringConfig.CaseConfigs {
			if caseConfig.GetCaseName() == caseName {
				return caseConfig
			}
		}
	}

	// 返回默认配置
	return scoringConfig.DefaultConfig
}

// ReloadReport 重载报告数据
// @route /apis/v1/report/reload [POST]
// 从 Pushgateway 重新查询原始数据并重新聚合，删除旧的 Chunk 数据并生成新的 Chunk
func (s *ReportHandler) ReloadReport(ctx context.Context, req *baseV1.IdRequest) *baseV1.Response {
	// 1. 参数校验
	reportID := req.GetID()
	if reportID == "" {
		return baseV1.Failed(fmt.Errorf("报告ID不能为空"), 1001)
	}

	// 2. 获取报告信息
	reportEntity, err := s.reportRepo.GetReport(ctx, reportID)
	if err != nil {
		return baseV1.Failed(fmt.Errorf("报告不存在: %v", err), int64(baseV1.BaseErrorCode_NOT_FOUND))
	}

	report := reportEntity.Resource
	if report == nil {
		return baseV1.Failed(fmt.Errorf("报告数据为空"), int64(baseV1.BaseErrorCode_NOT_FOUND))
	}

	// 3. 检查报告状态，如果正在处理中则拒绝重载
	if report.GetReportStatus() != nil && report.GetReportStatus().GetStatus() == string(taskpool.TaskStatusRunning) {
		return baseV1.Failed(fmt.Errorf("报告正在处理中，请稍后再试"), 1001)
	}

	// 4. 获取数据源信息
	datasource, err := s.datasourceRepo.GetDatasource(ctx, report.GetDatasourceID())
	if err != nil {
		return baseV1.Failed(fmt.Errorf("数据源查询失败: %v", err), int64(baseV1.BaseErrorCode_NOT_FOUND))
	}

	// 5. 更新报告状态为 running
	report.ReportStatus = &reportV1.ReportStatus{
		Status: string(taskpool.TaskStatusRunning),
	}
	s.reportRepo.UpdateReportStatus(ctx, reportID, report.GetReportStatus())

	// 6. 提交异步任务
	taskID := s.taskPool.Submit(
		"reload_report",
		func(task *taskpool.Task) error {
			return s.processReloadReport(context.Background(), reportEntity, datasource, task)
		},
		taskpool.WithTaskName(fmt.Sprintf("重载报告: %s", report.GetName())),
		taskpool.WithTaskMetadata(map[string]any{
			"report_id":   reportID,
			"total_cases": len(report.GetCases()),
		}),
		// 完成回调
		taskpool.WithOnComplete(func() {
			s.reportRepo.UpdateReportStatus(context.Background(), reportID, &reportV1.ReportStatus{
				Status: string(taskpool.TaskStatusCompleted),
			})
			logger.Info("report %s reload completed via callback", reportID)
		}),
		// 错误回调
		taskpool.WithOnError(func(err error) {
			s.reportRepo.UpdateReportStatus(context.Background(), reportID, &reportV1.ReportStatus{
				Status:   string(taskpool.TaskStatusFailed),
				ErrorMsg: err.Error(),
			})
			logger.Error("report %s reload failed via callback: %v", reportID, err)
		}),
	)

	// 更新 task_id
	report.GetReportStatus().TaskID = taskID
	s.reportRepo.UpdateReportStatus(ctx, reportID, report.GetReportStatus())

	logger.Info("report %s reload submitted as task %s", reportID, taskID)

	return baseV1.Success(baseV1.WithData(map[string]any{
		"report_id": reportID,
		"task_id":   taskID,
		"status":    "running",
	}))
}

// processReloadReport 处理报告重载（异步任务执行函数）
func (s *ReportHandler) processReloadReport(
	ctx context.Context,
	report *repo.ReportDocument,
	datasource *repo.DatasourceDocument,
	task *taskpool.Task,
) error {
	reportID := report.Id
	cases := report.Resource.GetCases()
	totalCases := len(cases)

	logger.Info("start reloading report %s with %d cases", reportID, totalCases)

	// 1. 删除旧的 Chunk 数据（硬删除）
	for _, singleCase := range cases {
		oldChunkIDs := getCaseChunkIDs(singleCase)
		for _, oldChunkID := range oldChunkIDs {
			// 先清除缓存
			s.chunkCache.Delete(oldChunkID)

			// 硬删除数据库中的 chunk
			if err := s.reportRepo.DeleteChunk(ctx, oldChunkID); err != nil {
				logger.Warn("删除旧 chunk 失败 chunk_id: %s, error: %v", oldChunkID, err)
				// 继续执行，不中断流程
			} else {
				logger.Info("删除旧 chunk 成功 chunk_id: %s", oldChunkID)
			}
		}

		// 清空用例的 chunk_ids（后面会重新赋值）
		singleCase.ChunkID = nil
		singleCase.ChunkIDs = nil
	}

	// 2. 重新生成所有 Chunk（复用 processReport 的逻辑）
	metricNamesMap := make(map[string]bool)

	for i, singleCase := range cases {
		// 检查任务是否被取消
		select {
		case <-task.CancelChan():
			logger.Warn("report %s reload cancelled", reportID)
			return fmt.Errorf("report reload cancelled")
		default:
		}

		// 计算进度
		caseProgressStart := int32(i * 100 / totalCases)
		caseProgressEnd := int32((i + 1) * 100 / totalCases)

		var lastProgressLogTime time.Time
		const progressLogCooldown = time.Second

		onProgress := func(info ProgressInfo) {
			globalProgress := caseProgressStart + (caseProgressEnd-caseProgressStart)*info.Progress/100

			groupStr := ""
			if info.CaseStr != "" {
				groupStr += fmt.Sprintf("case(%s)", info.CaseStr)
			}
			if info.FilterStr != "" {
				groupStr += fmt.Sprintf(" filter(%s)", info.FilterStr)
			}
			if info.WindowStr != "" {
				groupStr += fmt.Sprintf(" window(%s)", info.WindowStr)
			}

			now := time.Now()
			if groupStr != "" {
				if lastProgressLogTime.IsZero() || now.Sub(lastProgressLogTime) >= progressLogCooldown {
					logger.Debug("report %s reload %s progress: %d%%", reportID, groupStr, globalProgress)
					lastProgressLogTime = now
				}
			} else {
				logger.Info("report %s reload progress: %d%%", reportID, globalProgress)
			}

			task.UpdateProgress(globalProgress)
		}

		// 处理单个用例，生成新的 chunk
		chunkIDs, err := s.processSingleCase(ctx, reportID, singleCase, datasource, onProgress, fmt.Sprintf("%d/%d", i+1, totalCases), metricNamesMap)
		if err != nil {
			return fmt.Errorf("reload case %s failed: %w", singleCase.GetStressID(), err)
		}
		setCaseChunkIDs(singleCase, chunkIDs)
		task.UpdateProgress(caseProgressEnd)
	}

	// 3. 更新指标名称列表
	if len(metricNamesMap) > 0 {
		metricNames := make([]string, 0, len(metricNamesMap))
		for name := range metricNamesMap {
			metricNames = append(metricNames, name)
		}

		// 字典序排序
		for i := 0; i < len(metricNames); i++ {
			for j := i + 1; j < len(metricNames); j++ {
				if metricNames[i] > metricNames[j] {
					metricNames[i], metricNames[j] = metricNames[j], metricNames[i]
				}
			}
		}

		if report.Resource.MetricInfo == nil {
			report.Resource.MetricInfo = &reportV1.MetricInfo{}
		}
		report.Resource.MetricInfo.MetricNameList = metricNames

		logger.Info("重载报告收集到 %d 个指标名称", len(metricNames))
	}

	// 4. 保存报告更新
	if _, err := s.reportRepo.UpdateReportDocument(ctx, report); err != nil {
		return fmt.Errorf("保存报告失败: %w", err)
	}

	// 5. 如果配置了评分，重新计算评分
	if report.Resource.ScoringConfig != nil && report.Resource.ScoringConfig.DefaultConfig != nil {
		logger.Info("报告配置了评分标准，开始重新计算评分")
		if err := s.recalculateReportScore(ctx, report); err != nil {
			logger.Error("重新计算评分失败: %v", err)
			// 评分失败不影响重载流程
		}
	}

	logger.Info("report %s reload finished", reportID)
	return nil
}

// recalculateReportScore 重新计算报告评分
func (s *ReportHandler) recalculateReportScore(ctx context.Context, report *repo.ReportDocument) error {
	reportResource := report.Resource
	cases := reportResource.GetCases()

	caseScores := make([]*reportV1.CaseScore, 0, len(cases))

	for _, singleCase := range cases {
		chunkIDs := getCaseChunkIDs(singleCase)
		if len(chunkIDs) == 0 {
			continue
		}

		// 加载 chunk 数据
		chunkData, err := s.getChunkDataByIDs(ctx, chunkIDs)
		if err != nil {
			logger.Error("加载用例chunk数据失败 case_name: %s, error: %v", singleCase.GetName(), err)
			continue
		}

		// 转换为 thrift 格式
		thriftTables := make([]*pointsV1.SummaryTable, len(chunkData.Tables))
		for i, table := range chunkData.Tables {
			thriftTables[i] = &pointsV1.SummaryTable{
				Name:  table.Name,
				Table: table.Table,
			}
		}

		// 获取该用例的评分配置
		caseConfig := s.getCaseConfigForCase(reportResource.ScoringConfig, singleCase.GetName())

		// 计算用例得分（传入 Rate 统计数据用于评分）
		caseScore, err := scoring.CalculateCaseScore(thriftTables, caseConfig, singleCase.GetName(), singleCase.RateStatistics)
		if err != nil {
			logger.Error("计算用例得分失败 case_name: %s, error: %v", singleCase.GetName(), err)
			continue
		}

		caseScores = append(caseScores, caseScore)
	}

	if len(caseScores) == 0 {
		logger.Warn("没有任何用例成功计算得分")
		return nil
	}

	// 计算报告总分
	reportScore := scoring.CalculateReportScore(caseScores)
	reportResource.ReportScore = reportScore

	// 保存到数据库
	report.Resource = reportResource
	if _, err := s.reportRepo.UpdateReportDocument(ctx, report); err != nil {
		return fmt.Errorf("保存报告评分失败: %w", err)
	}

	logger.Info("报告评分重新计算完成 total_score: %.2f, level: %s", reportScore.TotalScore, reportScore.Level)
	return nil
}

// ForwardReport 转发报告到其他 MonitorHub（包含完整的 Chunk 数据）
// @route /apis/v1/report/forward [POST]
func (s *ReportHandler) ForwardReport(ctx context.Context, req *reportV1.ForwardReportRequest) *baseV1.Response {
	logger.Info("[ForwardReport] 开始转发报告: target_url=%s, report_id=%s", req.GetTargetURL(), req.GetReportID())

	// 1. 参数验证
	if req.GetTargetURL() == "" {
		return baseV1.Failed(fmt.Errorf("目标地址不能为空"), int64(baseV1.BaseErrorCode_INVALID_PARAM))
	}
	if req.GetReportID() == "" {
		return baseV1.Failed(fmt.Errorf("报告ID不能为空"), int64(baseV1.BaseErrorCode_INVALID_PARAM))
	}

	// 2. 获取本地报告数据
	reportDoc, err := s.reportRepo.GetReport(ctx, req.GetReportID())
	if err != nil {
		return baseV1.Failed(fmt.Errorf("获取报告失败: %w", err), int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	if reportDoc == nil {
		return baseV1.Failed(fmt.Errorf("报告不存在: %s", req.GetReportID()), int64(baseV1.BaseErrorCode_NOT_FOUND))
	}

	// 3. 获取所有关联的 Chunk 数据，同时收集 Chunk ID
	var chunks []*reportV1.Chunk
	var chunkIDs []string
	for _, singleCase := range reportDoc.Resource.GetCases() {
		caseChunkIDs := getCaseChunkIDs(singleCase)
		for _, cid := range caseChunkIDs {
			chunkDoc, err := s.reportRepo.GetChunk(ctx, cid)
			if err != nil {
				logger.Warn("获取 Chunk 失败: chunkId=%s, err=%v", cid, err)
				continue
			}
			if chunkDoc != nil {
				chunks = append(chunks, chunkDoc.Resource)
				chunkIDs = append(chunkIDs, chunkDoc.Id) // 保存原始 Chunk ID
			}
		}
	}

	// 修改创建方式为 api_call（表示通过接口转发）
	reportDoc.Resource.CreateType = "api_call"

	// 4. 构造转发请求体（包含报告、Chunk 和原始 ID）
	forwardPayload := map[string]interface{}{
		"source_id": reportDoc.Id, // 原始报告 ID
		"report":    reportDoc.Resource,
		"chunks":    chunks,
		"chunk_ids": chunkIDs, // 原始 Chunk ID 列表
	}

	// 5. 发送请求到目标 MonitorHub 的导入接口
	targetURL := strings.TrimSuffix(req.GetTargetURL(), "/") + "/apis/v1/report/import"
	respData, err := forwardReportHTTPRequest(ctx, targetURL, forwardPayload)
	if err != nil {
		// 如果导入接口不存在，尝试调用普通的 create 接口
		logger.Warn("调用导入接口失败，尝试调用创建接口: %v", err)
		targetURL = strings.TrimSuffix(req.GetTargetURL(), "/") + "/apis/v1/report/create"
		respData, err = forwardReportHTTPRequest(ctx, targetURL, reportDoc.Resource)
		if err != nil {
			return baseV1.Failed(fmt.Errorf("转发报告失败: %w", err), int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
		}
		return baseV1.Success(baseV1.WithData(map[string]interface{}{
			"message":         "报告转发成功（仅元数据，需目标机器有对应数据源）",
			"source_id":       req.GetReportID(),
			"target_url":      req.GetTargetURL(),
			"chunk_count":     len(chunks),
			"target_response": respData,
		}))
	}

	return baseV1.Success(baseV1.WithData(map[string]interface{}{
		"message":         "报告转发成功（包含完整数据）",
		"source_id":       req.GetReportID(),
		"target_url":      req.GetTargetURL(),
		"chunk_count":     len(chunks),
		"target_response": respData,
	}))
}

// forwardReportHTTPRequest 发送 HTTP POST 请求到目标 URL
func forwardReportHTTPRequest(ctx context.Context, targetURL string, payload interface{}) (map[string]interface{}, error) {
	logger.Info("[ForwardReport] 准备发送请求到: %s", targetURL)

	// 序列化请求体
	body, err := sonic.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("序列化请求体失败: %w", err)
	}
	logger.Info("[ForwardReport] 请求体大小: %d bytes", len(body))

	// 创建 HTTP 请求
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, targetURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("创建请求失败: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	// 发送请求（设置超时，报告数据可能较大，给更长时间）
	client := &http.Client{Timeout: 120 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("发送请求失败: %w", err)
	}
	defer resp.Body.Close()

	logger.Info("[ForwardReport] 收到响应: HTTP %d", resp.StatusCode)

	// 读取响应
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("读取响应失败: %w", err)
	}

	logger.Info("[ForwardReport] 响应内容 (%d bytes): %s", len(respBody), string(respBody[:min(len(respBody), 500)]))

	// 检查是否返回了 HTML（说明目标服务器路由问题）
	if len(respBody) > 0 && (respBody[0] == '<' || bytes.HasPrefix(respBody, []byte("<!DOCTYPE"))) {
		return nil, fmt.Errorf("目标服务器返回了 HTML 页面（可能是路由不存在或服务未启动）")
	}

	// 检查空响应
	if len(respBody) == 0 {
		return nil, fmt.Errorf("目标服务器返回空响应 (HTTP %d)", resp.StatusCode)
	}

	// 解析响应
	var result map[string]interface{}
	if err := sonic.Unmarshal(respBody, &result); err != nil {
		return nil, fmt.Errorf("解析响应失败: %w, 响应内容: %s", err, string(respBody[:min(len(respBody), 200)]))
	}

	// 检查响应码
	if resp.StatusCode != http.StatusOK {
		return result, fmt.Errorf("目标服务返回错误: HTTP %d", resp.StatusCode)
	}

	// 检查业务响应码
	if code, ok := result["code"].(float64); ok && code != 0 {
		msg := ""
		if m, ok := result["msg"].(string); ok {
			msg = m
		}
		return result, fmt.Errorf("目标服务业务错误: code=%v, msg=%s", code, msg)
	}

	return result, nil
}

// ImportReport 导入报告（从其他 MonitorHub 转发过来，保持原始ID）
// @route /apis/v1/report/import [POST]
func (s *ReportHandler) ImportReport(ctx context.Context, req *reportV1.ImportReportRequest) *baseV1.Response {
	logger.Info("[ImportReport] 开始导入报告: source_id=%s, name=%s", req.GetSourceID(), req.GetReport().GetName())

	// 1. 参数验证
	if req.GetSourceID() == "" {
		return baseV1.Failed(fmt.Errorf("源报告ID不能为空"), int64(baseV1.BaseErrorCode_INVALID_PARAM))
	}
	if req.GetReport() == nil {
		return baseV1.Failed(fmt.Errorf("报告数据不能为空"), int64(baseV1.BaseErrorCode_INVALID_PARAM))
	}

	// 2. 检查报告是否已存在（避免重复导入）
	existingReport, err := s.reportRepo.GetReport(ctx, req.GetSourceID())
	if err == nil && existingReport != nil {
		logger.Warn("[ImportReport] 报告已存在，跳过导入: id=%s", req.GetSourceID())
		return baseV1.Success(baseV1.WithData(map[string]interface{}{
			"message":   "报告已存在，跳过导入",
			"report_id": req.GetSourceID(),
			"existed":   true,
		}))
	}

	// 3. 创建报告（使用原始ID）
	createdReport, err := s.reportRepo.CreateReportWithID(ctx, req.GetSourceID(), req.GetReport())
	if err != nil {
		return baseV1.Failed(fmt.Errorf("创建报告失败: %w", err), int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	logger.Info("[ImportReport] 报告创建成功: id=%s", createdReport.Id)

	// 4. 导入 Chunk 数据（如果有）
	chunks := req.GetChunks()
	chunkIDs := req.GetChunkIds()
	importedChunks := 0

	if len(chunks) > 0 {
		for i, chunk := range chunks {
			// 确定 Chunk ID
			var chunkID string
			if i < len(chunkIDs) && chunkIDs[i] != "" {
				chunkID = chunkIDs[i]
			} else {
				// 如果没有提供 chunk_id，尝试从 case 中获取
				for _, singleCase := range req.GetReport().GetCases() {
					if singleCase.GetStressID() == chunk.GetStressID() {
						// 优先从 chunk_ids 获取，回退到 chunk_id
						caseIDs := getCaseChunkIDs(singleCase)
						if len(caseIDs) > 0 {
							chunkID = caseIDs[0]
							break
						}
					}
				}
			}

			if chunkID == "" {
				logger.Warn("[ImportReport] Chunk 没有ID，跳过: stress_id=%s", chunk.GetStressID())
				continue
			}

			// 检查 Chunk 是否已存在
			existingChunk, err := s.reportRepo.GetChunk(ctx, chunkID)
			if err == nil && existingChunk != nil {
				logger.Info("[ImportReport] Chunk 已存在，跳过: id=%s", chunkID)
				continue
			}

			// 更新 Chunk 的 report_id 为新的报告 ID
			chunk.ReportID = createdReport.Id

			// 创建 Chunk（使用原始ID）
			_, err = s.reportRepo.CreateChunkWithID(ctx, chunkID, chunk)
			if err != nil {
				logger.Warn("[ImportReport] 创建 Chunk 失败: id=%s, err=%v", chunkID, err)
				continue
			}
			importedChunks++
			logger.Info("[ImportReport] Chunk 导入成功: id=%s", chunkID)
		}
	}

	return baseV1.Success(baseV1.WithData(map[string]interface{}{
		"message":         "报告导入成功",
		"report_id":       createdReport.Id,
		"imported_chunks": importedChunks,
		"total_chunks":    len(chunks),
	}))
}
