// Code generated by hzx generator. DO NOT EDIT.
package v1

import (
	"context"
	baseV1 "monitor_hub/apis/monitor_hub/base/v1"
	v1 "monitor_hub/apis/monitor_hub/report/v1"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

type ReportService struct {
	handler *ReportHandler
}

func NewReportService(handler *ReportHandler) *ReportService {
	return &ReportService{handler: handler}
}

// CreateReport
// @route /apis/v1/report/create [POST]
func (s *ReportService) CreateReport(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.Report
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.CreateReport(ctx, &req))
}

// GetReport
// @route /apis/v1/report/get [POST]
func (s *ReportService) GetReport(ctx context.Context, c *app.RequestContext) {
	var err error
	var req baseV1.IdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.GetReport(ctx, &req))
}

// GetChunk
// @route /apis/v1/report/chunk/get [POST]
func (s *ReportService) GetChunk(ctx context.Context, c *app.RequestContext) {
	var err error
	var req baseV1.IdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.GetChunk(ctx, &req))
}

// ListReport
// @route /apis/v1/report/list [POST]
func (s *ReportService) ListReport(ctx context.Context, c *app.RequestContext) {
	var err error
	var req baseV1.QueryRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.ListReport(ctx, &req))
}

// DeleteReport
// @route /apis/v1/report/del [POST]
func (s *ReportService) DeleteReport(ctx context.Context, c *app.RequestContext) {
	var err error
	var req baseV1.IdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.DeleteReport(ctx, &req))
}

// GetReportTask
// @route /apis/v1/report/task/get [POST]
func (s *ReportService) GetReportTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req baseV1.IdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.GetReportTask(ctx, &req))
}

// GetReportChunkList
// @route /apis/v1/report/chunk/list [POST]
func (s *ReportService) GetReportChunkList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req baseV1.IdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.GetReportChunkList(ctx, &req))
}

// UpdateReport
// @route /apis/v1/report/update [POST]
func (s *ReportService) UpdateReport(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.UpdateReportRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.UpdateReport(ctx, &req))
}

// UploadIcon
// @route /apis/v1/report/icon/upload [POST]
func (s *ReportService) UploadIcon(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.UploadIconRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.UploadIcon(ctx, &req))
}

// CalculateReportScore
// @route /apis/v1/report/score/calculate [POST]
func (s *ReportService) CalculateReportScore(ctx context.Context, c *app.RequestContext) {
	var err error
	var req baseV1.IdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.CalculateReportScore(ctx, &req))
}

// ReloadReport
// @route /apis/v1/report/reload [POST]
func (s *ReportService) ReloadReport(ctx context.Context, c *app.RequestContext) {
	var err error
	var req baseV1.IdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.ReloadReport(ctx, &req))
}

// ForwardReport
// @route /apis/v1/report/forward [POST]
func (s *ReportService) ForwardReport(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.ForwardReportRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.ForwardReport(ctx, &req))
}

// ImportReport 导入报告（从其他 MonitorHub 转发过来，保持原始ID）
// @route /apis/v1/report/import [POST]
func (s *ReportService) ImportReport(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.ImportReportRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.ImportReport(ctx, &req))
}
