// Code generated by hzx generator.
package v1

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	baseV1 "monitor_hub/apis/monitor_hub/base/v1"
	v1 "monitor_hub/apis/monitor_hub/datasource/v1"
	configV1 "monitor_hub/config/v1"
	websocket "monitor_hub/internal/websocket"
	repo "monitor_hub/pkg/repo"
)

type DatasourceHandler struct {
	cfg                   *configV1.Config
	datasourceRepo        repo.DatasourceRepo
	wsServer              *websocket.Server
	datasourceBroadcaster *DatasourceBroadcaster
}

func NewDatasourceHandler(cfg *configV1.Config, datasourceRepo repo.DatasourceRepo, wsServer *websocket.Server, datasourceBroadcaster *DatasourceBroadcaster) *DatasourceHandler {
	return &DatasourceHandler{
		cfg:                   cfg,
		datasourceRepo:        datasourceRepo,
		wsServer:              wsServer,
		datasourceBroadcaster: datasourceBroadcaster,
	}
}

// CreateDatasource
// @route /apis/v1/datasource/create [POST]
func (s *DatasourceHandler) CreateDatasource(ctx context.Context, req *v1.CreateDatasourceRequest) *baseV1.Response {
	// 查询判断是否已存在,存在不允许创建
	exist, err := s.datasourceRepo.IsDatasourceExist(ctx, req.Datasource.Name, req.Datasource.AppID)
	if err != nil {
		return baseV1.Failed(err, int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	if exist {
		return baseV1.Failed(
			fmt.Errorf("app_id(%v) name(%v) datasource already exists", req.Datasource.AppID, req.Datasource.Name),
			int64(baseV1.BaseErrorCode_RESOURCE_ALREADY_EXISTS),
		)
	}
	// 创建数据源
	doc, err := s.datasourceRepo.CreateDatasource(ctx, req.Datasource)
	if err != nil {
		return baseV1.Failed(err, int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	return baseV1.Success(baseV1.WithData(doc))
}

// UpdateDatasource
// @route /apis/v1/datasource/update [POST]
func (s *DatasourceHandler) UpdateDatasource(ctx context.Context, req *v1.UpdateDatasourceRequest) *baseV1.Response {
	// Id必填，Id不存在不允许更新
	// 如果更新name或app_id，要确保和其他数据源不重复
	doc, err := s.datasourceRepo.GetDatasource(ctx, req.ID)
	if err != nil {
		return baseV1.Failed(err, int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	if doc == nil {
		return baseV1.Failed(fmt.Errorf("id(%v) datasource not found", req.ID), int64(baseV1.BaseErrorCode_NOT_FOUND))
	}
	// 如果更新name或app_id，要确保和其他数据源不重复
	if doc.Resource.Name != req.Datasource.Name || doc.Resource.AppID != req.Datasource.AppID {
		// 验证新的name和app_id组合是否重复
		exist, err := s.datasourceRepo.IsDatasourceExist(ctx, req.Datasource.Name, req.Datasource.AppID)
		if err != nil {
			return baseV1.Failed(err, int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
		}
		if exist {
			return baseV1.Failed(fmt.Errorf("new app_id(%v) name(%v) datasource already exists", req.Datasource.AppID, req.Datasource.Name), int64(baseV1.BaseErrorCode_RESOURCE_ALREADY_EXISTS))
		}
	}
	// 更新数据源
	doc, err = s.datasourceRepo.UpdateDatasource(ctx, req.ID, req.Datasource)
	if err != nil {
		return baseV1.Failed(err, int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	return baseV1.Success(baseV1.WithData(doc))
}

// GetDatasource
// @route /apis/v1/datasource/get [POST]
func (s *DatasourceHandler) GetDatasource(ctx context.Context, req *baseV1.IdRequest) *baseV1.Response {
	// 查询判断是否存在,不存在不允许查询
	doc, err := s.datasourceRepo.GetDatasource(ctx, req.ID)
	if err != nil {
		return baseV1.Failed(err, int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	if doc == nil {
		return baseV1.Failed(
			fmt.Errorf("id(%v) datasource not found", req.ID),
			int64(baseV1.BaseErrorCode_NOT_FOUND),
		)
	}
	return baseV1.Success(baseV1.WithData(doc))
}

// ListDatasource
// @route /apis/v1/datasource/list [POST]
func (s *DatasourceHandler) ListDatasource(ctx context.Context, req *baseV1.QueryRequest) *baseV1.Response {
	docs, page, err := s.datasourceRepo.ListDatasource(ctx, req)
	if err != nil {
		return baseV1.Failed(err, int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	return baseV1.Success(baseV1.WithData(docs), baseV1.WithPage(page))
}

// DeleteDatasource
// @route /apis/v1/datasource/del [POST]
func (s *DatasourceHandler) DeleteDatasource(ctx context.Context, req *baseV1.IdRequest) *baseV1.Response {
	err := s.datasourceRepo.DeleteDatasource(ctx, req.ID)
	if err != nil {
		return baseV1.Failed(err, int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	return baseV1.Success()
}

// ============================================
// WebSocket Handlers
// ============================================

// WsSubscribeStatus
// @route subscribe.datasource.status [WEBSOCKET]
func (s *DatasourceHandler) WsSubscribeDatasourceStatus(ctx context.Context, conn *websocket.Connection, env *websocket.Envelope) *websocket.WsResponse {
	// 1. 解析请求参数
	var req v1.SubscribeDatasourceStatusRequest
	if err := env.UnmarshalData(&req); err != nil {
		logger.Warn("(Connection: %s) Failed to parse subscribe request: %v", conn.ID, err)
		return websocket.WsFailed(err, websocket.ERR_CODE_INVALID_REQUEST)
	}

	logger.Info("(Connection: %s) Subscribe to datasource.status, datasource_ids: %v, include_details: %v",
		conn.ID, req.DatasourceIds, req.IncludeDetails)

	// 添加订阅
	subManager := s.wsServer.GetSubscriptionManager()
	subManager.Subscribe(conn.ID, env.Topic, &req)

	// 订阅成功后，立即广播一次
	logger.Info("(DatasourceHandler) WsSubscribeStatus Triggering status broadcast")
	subscription, _ := subManager.GetSubscriptionByConnIDAndTopic(conn.ID, env.Topic)
	bctx := websocket.NewBroadcastContext(ctx, subscription, env.Topic, nil, "manual")
	s.wsServer.BroadcastOne(bctx, s.datasourceBroadcaster)

	logger.Info("(Connection: %s) Successfully subscribed to topic: %s", conn.ID, env.Topic)

	// 发送订阅成功响应
	return websocket.WsSuccess()
}

// WsUnsubscribeStatus
// @route unsubscribe.datasource.status [WEBSOCKET]
func (s *DatasourceHandler) WsUnsubscribeDatasourceStatus(ctx context.Context, conn *websocket.Connection, env *websocket.Envelope) *websocket.WsResponse {
	// 1. 解析请求参数
	var req v1.UnsubscribeRequest
	if err := env.UnmarshalData(&req); err != nil {
		logger.Warn("(Connection: %s) Failed to parse unsubscribe request: %v", conn.ID, err)
		return websocket.WsFailed(err, websocket.ERR_CODE_INVALID_REQUEST)
	}

	logger.Info("(Connection: %s) Unsubscribe from topic: %s", conn.ID, req.Topic)

	// 2. 取消订阅
	subManager := s.wsServer.GetSubscriptionManager()
	success := subManager.Unsubscribe(conn.ID, req.Topic)

	if !success {
		logger.Warn("(Connection: %s) Not subscribed to topic: %s", conn.ID, req.Topic)
		return websocket.WsFailed(fmt.Errorf("未订阅该主题"), websocket.ERR_CODE_INVALID_TOPIC)
	}

	logger.Info("(Connection: %s) Successfully unsubscribed from topic: %s", conn.ID, req.Topic)
	// 发送取消订阅成功响应
	return websocket.WsSuccess()
}

// UploadIcon 上传数据源图标
// @route /apis/v1/datasource/icon/upload [POST]
func (s *DatasourceHandler) UploadIcon(ctx context.Context, req *v1.UploadIconRequest) *baseV1.Response {
	// 1. 验证数据源是否存在
	doc, err := s.datasourceRepo.GetDatasource(ctx, req.DatasourceID)
	if err != nil {
		return baseV1.Failed(err, int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	if doc == nil {
		return baseV1.Failed(
			fmt.Errorf("datasource(%v) not found", req.DatasourceID),
			int64(baseV1.BaseErrorCode_NOT_FOUND),
		)
	}

	// 2. 验证文件扩展名（只允许 png/svg/jpg/jpeg）
	ext := strings.ToLower(filepath.Ext(req.FileName))
	allowedExts := map[string]bool{".png": true, ".svg": true, ".jpg": true, ".jpeg": true}
	if !allowedExts[ext] {
		return baseV1.Failed(
			fmt.Errorf("不支持的文件格式: %s, 仅支持 png/svg/jpg/jpeg", ext),
			int64(baseV1.BaseErrorCode_INVALID_PARAM),
		)
	}

	// 3. 验证文件魔数（防止伪造扩展名的恶意文件）
	if !validateImageMagicNumber(req.IconData, ext) {
		return baseV1.Failed(
			fmt.Errorf("文件内容与扩展名不匹配，可能存在安全风险"),
			int64(baseV1.BaseErrorCode_INVALID_PARAM),
		)
	}

	// 4. 清理文件名（防止路径注入）
	safeFileName := sanitizeFileName(req.FileName)
	if safeFileName == "" {
		return baseV1.Failed(
			fmt.Errorf("无效的文件名"),
			int64(baseV1.BaseErrorCode_INVALID_PARAM),
		)
	}

	// 5. 获取可执行文件所在目录，创建 icon/{数据源ID}/ 目录
	execPath, err := os.Executable()
	if err != nil {
		return baseV1.Failed(
			fmt.Errorf("获取可执行文件路径失败: %w", err),
			int64(baseV1.BaseErrorCode_INTERNAL_ERROR),
		)
	}
	execDir := filepath.Dir(execPath)
	iconDir := filepath.Join(execDir, "icon", req.DatasourceID)

	// 创建目录（如果不存在）
	if err := os.MkdirAll(iconDir, 0755); err != nil {
		return baseV1.Failed(
			fmt.Errorf("创建图标目录失败: %w", err),
			int64(baseV1.BaseErrorCode_INTERNAL_ERROR),
		)
	}

	// 6. 保存文件
	iconPath := filepath.Join(iconDir, safeFileName)
	if err := os.WriteFile(iconPath, req.IconData, 0644); err != nil {
		return baseV1.Failed(
			fmt.Errorf("保存图标文件失败: %w", err),
			int64(baseV1.BaseErrorCode_INTERNAL_ERROR),
		)
	}

	// 7. 更新数据库中的 icon_name
	updatedDoc, err := s.datasourceRepo.UpdateDatasourceIconName(ctx, req.DatasourceID, safeFileName)
	if err != nil {
		// 如果数据库更新失败，删除已保存的文件
		os.Remove(iconPath)
		return baseV1.Failed(
			fmt.Errorf("更新数据库失败: %w", err),
			int64(baseV1.BaseErrorCode_INTERNAL_ERROR),
		)
	}

	logger.Info("(DatasourceHandler) UploadIcon: datasource_id=%s, icon_name=%s, saved_path=%s",
		req.DatasourceID, safeFileName, iconPath)

	return baseV1.Success(baseV1.WithData(updatedDoc))
}

// validateImageMagicNumber 验证图片文件的魔数（文件头）
// 防止用户上传伪装成图片的恶意文件
func validateImageMagicNumber(data []byte, ext string) bool {
	if len(data) < 8 {
		return false
	}

	switch ext {
	case ".png":
		// PNG 魔数: 89 50 4E 47 0D 0A 1A 0A
		pngMagic := []byte{0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A}
		return bytes.HasPrefix(data, pngMagic)
	case ".jpg", ".jpeg":
		// JPEG 魔数: FF D8 FF
		jpegMagic := []byte{0xFF, 0xD8, 0xFF}
		return bytes.HasPrefix(data, jpegMagic)
	case ".svg":
		// SVG 是 XML 文本格式，检查是否以 <?xml 或 <svg 开头
		// 去除可能的 BOM 头
		content := bytes.TrimLeft(data, "\xef\xbb\xbf") // UTF-8 BOM
		contentStr := strings.TrimSpace(string(content[:min(len(content), 1024)]))
		return strings.HasPrefix(contentStr, "<?xml") ||
			strings.HasPrefix(contentStr, "<svg") ||
			strings.HasPrefix(contentStr, "<!DOCTYPE svg")
	default:
		return false
	}
}

// sanitizeFileName 清理文件名，防止路径遍历攻击
func sanitizeFileName(fileName string) string {
	// 只保留文件名部分（去除路径）
	fileName = filepath.Base(fileName)

	// 只允许字母、数字、下划线、连字符、点
	reg := regexp.MustCompile(`[^a-zA-Z0-9_\-.]`)
	fileName = reg.ReplaceAllString(fileName, "_")

	// 防止 .. 和 空文件名
	if fileName == "" || fileName == "." || fileName == ".." {
		return ""
	}

	// 限制文件名长度
	if len(fileName) > 100 {
		ext := filepath.Ext(fileName)
		name := strings.TrimSuffix(fileName, ext)
		if len(name) > 100-len(ext) {
			name = name[:100-len(ext)]
		}
		fileName = name + ext
	}

	return fileName
}
