// Code generated by hzx generator.
package v1

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	baseV1 "monitor_hub/apis/monitor_hub/base/v1"
	v1 "monitor_hub/apis/monitor_hub/task/v1"
	configV1 "monitor_hub/config/v1"
	websocket "monitor_hub/internal/websocket"
	repo "monitor_hub/pkg/repo"

	"github.com/bytedance/sonic"
)

type TaskHandler struct {
	cfg      *configV1.Config
	wsServer *websocket.Server
	taskRepo repo.TaskRepo
}

func NewTaskHandler(cfg *configV1.Config, wsServer *websocket.Server, taskRepo repo.TaskRepo) *TaskHandler {
	return &TaskHandler{
		cfg:      cfg,
		wsServer: wsServer,
		taskRepo: taskRepo,
	}
}

// CreateTask
// @route /apis/v1/task/create [POST]
func (s *TaskHandler) CreateTask(ctx context.Context, req *v1.CreateTaskRequest) *baseV1.Response {
	// 验证必填字段
	if req.Task == nil {
		return baseV1.Failed(fmt.Errorf("task is required"), int64(baseV1.BaseErrorCode_INVALID_PARAM))
	}
	if req.Task.Name == "" {
		return baseV1.Failed(fmt.Errorf("task name is required"), int64(baseV1.BaseErrorCode_INVALID_PARAM))
	}

	// 设置默认创建方式
	if req.Task.CreateType == nil || *req.Task.CreateType == "" {
		createType := "web_manual"
		req.Task.CreateType = &createType
	}

	// 创建任务
	doc, err := s.taskRepo.CreateTask(ctx, req.Task)
	if err != nil {
		return baseV1.Failed(err, int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	return baseV1.Success(baseV1.WithData(doc))
}

// GetTask
// @route /apis/v1/task/get [POST]
func (s *TaskHandler) GetTask(ctx context.Context, req *baseV1.IdRequest) *baseV1.Response {
	// ID 必填
	if req.ID == "" {
		return baseV1.Failed(fmt.Errorf("task id is required"), int64(baseV1.BaseErrorCode_INVALID_PARAM))
	}

	// 查询任务
	doc, err := s.taskRepo.GetTask(ctx, req.ID)
	if err != nil {
		return baseV1.Failed(err, int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	if doc == nil {
		return baseV1.Failed(
			fmt.Errorf("id(%v) task not found", req.ID),
			int64(baseV1.BaseErrorCode_NOT_FOUND),
		)
	}
	return baseV1.Success(baseV1.WithData(doc))
}

// ListTask
// @route /apis/v1/task/list [POST]
func (s *TaskHandler) ListTask(ctx context.Context, req *baseV1.QueryRequest) *baseV1.Response {
	docs, page, err := s.taskRepo.ListTask(ctx, req)
	if err != nil {
		return baseV1.Failed(err, int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	return baseV1.Success(baseV1.WithData(docs), baseV1.WithPage(page))
}

// UpdateTask
// @route /apis/v1/task/update [POST]
func (s *TaskHandler) UpdateTask(ctx context.Context, req *v1.UpdateTaskRequest) *baseV1.Response {
	// ID 必填
	if req.ID == "" {
		return baseV1.Failed(fmt.Errorf("task id is required"), int64(baseV1.BaseErrorCode_INVALID_PARAM))
	}
	if req.Task == nil {
		return baseV1.Failed(fmt.Errorf("task is required"), int64(baseV1.BaseErrorCode_INVALID_PARAM))
	}

	// 先检查任务是否存在
	existDoc, err := s.taskRepo.GetTask(ctx, req.ID)
	if err != nil {
		return baseV1.Failed(err, int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	if existDoc == nil {
		return baseV1.Failed(
			fmt.Errorf("id(%v) task not found", req.ID),
			int64(baseV1.BaseErrorCode_NOT_FOUND),
		)
	}

	// 增量更新任务
	doc, err := s.taskRepo.UpdateTask(ctx, req.ID, req.Task)
	if err != nil {
		return baseV1.Failed(err, int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	return baseV1.Success(baseV1.WithData(doc))
}

// DeleteTask
// @route /apis/v1/task/del [POST]
func (s *TaskHandler) DeleteTask(ctx context.Context, req *baseV1.IdRequest) *baseV1.Response {
	// ID 必填
	if req.ID == "" {
		return baseV1.Failed(fmt.Errorf("task id is required"), int64(baseV1.BaseErrorCode_INVALID_PARAM))
	}

	// 先检查任务是否存在
	existDoc, err := s.taskRepo.GetTask(ctx, req.ID)
	if err != nil {
		return baseV1.Failed(err, int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	if existDoc == nil {
		return baseV1.Failed(
			fmt.Errorf("id(%v) task not found", req.ID),
			int64(baseV1.BaseErrorCode_NOT_FOUND),
		)
	}

	// 删除任务
	err = s.taskRepo.DeleteTask(ctx, req.ID)
	if err != nil {
		return baseV1.Failed(err, int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	return baseV1.Success()
}

// UploadIcon
// @route /apis/v1/task/icon/upload [POST]
func (s *TaskHandler) UploadIcon(ctx context.Context, req *v1.UploadIconRequest) *baseV1.Response {
	// 1. 验证任务是否存在
	doc, err := s.taskRepo.GetTask(ctx, req.GetTaskID())
	if err != nil {
		return baseV1.Failed(err, int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	if doc == nil {
		return baseV1.Failed(
			fmt.Errorf("task(%v) not found", req.GetTaskID()),
			int64(baseV1.BaseErrorCode_NOT_FOUND),
		)
	}

	// 2. 验证文件扩展名（只允许 png/svg/jpg/jpeg）
	ext := strings.ToLower(filepath.Ext(req.FileName))
	allowedExts := map[string]bool{".png": true, ".svg": true, ".jpg": true, ".jpeg": true}
	if !allowedExts[ext] {
		return baseV1.Failed(
			fmt.Errorf("不支持的文件格式: %s, 仅支持 png/svg/jpg/jpeg", ext),
			int64(baseV1.BaseErrorCode_INVALID_PARAM),
		)
	}

	// 3. 验证文件魔数（防止伪造扩展名的恶意文件）
	if !validateTaskImageMagicNumber(req.IconData, ext) {
		return baseV1.Failed(
			fmt.Errorf("文件内容与扩展名不匹配，可能存在安全风险"),
			int64(baseV1.BaseErrorCode_INVALID_PARAM),
		)
	}

	// 4. 清理文件名（防止路径注入）
	safeFileName := sanitizeTaskFileName(req.FileName)
	if safeFileName == "" {
		return baseV1.Failed(
			fmt.Errorf("无效的文件名"),
			int64(baseV1.BaseErrorCode_INVALID_PARAM),
		)
	}

	// 5. 获取可执行文件所在目录，创建 icon/{任务ID}/ 目录
	execPath, err := os.Executable()
	if err != nil {
		return baseV1.Failed(
			fmt.Errorf("获取可执行文件路径失败: %w", err),
			int64(baseV1.BaseErrorCode_INTERNAL_ERROR),
		)
	}
	execDir := filepath.Dir(execPath)
	iconDir := filepath.Join(execDir, "icon", req.GetTaskID())

	// 创建目录（如果不存在）
	if err := os.MkdirAll(iconDir, 0755); err != nil {
		return baseV1.Failed(
			fmt.Errorf("创建图标目录失败: %w", err),
			int64(baseV1.BaseErrorCode_INTERNAL_ERROR),
		)
	}

	// 6. 保存文件
	iconPath := filepath.Join(iconDir, safeFileName)
	if err := os.WriteFile(iconPath, req.IconData, 0644); err != nil {
		return baseV1.Failed(
			fmt.Errorf("保存图标文件失败: %w", err),
			int64(baseV1.BaseErrorCode_INTERNAL_ERROR),
		)
	}

	// 7. 更新任务的 icon_name 字段
	updateTask := &v1.TestTask{
		IconName: &safeFileName,
	}
	updatedDoc, err := s.taskRepo.UpdateTask(ctx, req.GetTaskID(), updateTask)
	if err != nil {
		return baseV1.Failed(
			fmt.Errorf("更新任务图标信息失败: %w", err),
			int64(baseV1.BaseErrorCode_INTERNAL_ERROR),
		)
	}

	return baseV1.Success(baseV1.WithData(updatedDoc))
}

// validateTaskImageMagicNumber 验证图片文件的魔数（文件头）
func validateTaskImageMagicNumber(data []byte, ext string) bool {
	if len(data) < 8 {
		return false
	}

	switch ext {
	case ".png":
		pngMagic := []byte{0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A}
		return bytes.HasPrefix(data, pngMagic)
	case ".jpg", ".jpeg":
		jpegMagic := []byte{0xFF, 0xD8, 0xFF}
		return bytes.HasPrefix(data, jpegMagic)
	case ".svg":
		content := bytes.TrimLeft(data, "\xef\xbb\xbf")
		contentStr := strings.TrimSpace(string(content[:min(len(content), 1024)]))
		return strings.HasPrefix(contentStr, "<?xml") ||
			strings.HasPrefix(contentStr, "<svg") ||
			strings.HasPrefix(contentStr, "<!DOCTYPE svg")
	default:
		return false
	}
}

// sanitizeTaskFileName 清理文件名，防止路径遍历攻击
func sanitizeTaskFileName(fileName string) string {
	fileName = filepath.Base(fileName)
	reg := regexp.MustCompile(`[^a-zA-Z0-9_\-.]`)
	fileName = reg.ReplaceAllString(fileName, "_")

	if fileName == "" || fileName == "." || fileName == ".." {
		return ""
	}

	if len(fileName) > 100 {
		fileName = fileName[:100]
	}

	return fileName
}

// ForwardTask 转发任务到其他 MonitorHub
// @route /apis/v1/task/forward [POST]
func (s *TaskHandler) ForwardTask(ctx context.Context, req *v1.ForwardTaskRequest) *baseV1.Response {
	// 1. 参数验证
	if req.GetTargetURL() == "" {
		return baseV1.Failed(fmt.Errorf("目标地址不能为空"), int64(baseV1.BaseErrorCode_INVALID_PARAM))
	}
	if req.GetTaskID() == "" {
		return baseV1.Failed(fmt.Errorf("任务ID不能为空"), int64(baseV1.BaseErrorCode_INVALID_PARAM))
	}

	// 2. 获取本地任务数据
	taskDoc, err := s.taskRepo.GetTask(ctx, req.GetTaskID())
	if err != nil {
		return baseV1.Failed(fmt.Errorf("获取任务失败: %w", err), int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}
	if taskDoc == nil {
		return baseV1.Failed(fmt.Errorf("任务不存在: %s", req.GetTaskID()), int64(baseV1.BaseErrorCode_NOT_FOUND))
	}

	// 3. 构造创建任务请求
	createReq := &v1.CreateTaskRequest{
		Task: taskDoc.Resource,
	}

	// 修改创建方式为 api_call（表示通过接口转发）
	createType := "api_call"
	createReq.Task.CreateType = &createType

	// 4. 发送请求到目标 MonitorHub
	targetURL := strings.TrimSuffix(req.GetTargetURL(), "/") + "/apis/v1/task/create"
	respData, err := forwardHTTPRequest(ctx, targetURL, createReq)
	if err != nil {
		return baseV1.Failed(fmt.Errorf("转发任务失败: %w", err), int64(baseV1.BaseErrorCode_INTERNAL_ERROR))
	}

	return baseV1.Success(baseV1.WithData(map[string]interface{}{
		"message":         "任务转发成功",
		"source_id":       req.GetTaskID(),
		"target_url":      req.GetTargetURL(),
		"target_response": respData,
	}))
}

// forwardHTTPRequest 发送 HTTP POST 请求到目标 URL
func forwardHTTPRequest(ctx context.Context, targetURL string, payload interface{}) (map[string]interface{}, error) {
	// 序列化请求体
	body, err := sonic.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("序列化请求体失败: %w", err)
	}

	// 创建 HTTP 请求
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, targetURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("创建请求失败: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	// 发送请求（设置超时）
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("发送请求失败: %w", err)
	}
	defer resp.Body.Close()

	// 读取响应
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("读取响应失败: %w", err)
	}

	// 解析响应
	var result map[string]interface{}
	if err := sonic.Unmarshal(respBody, &result); err != nil {
		return nil, fmt.Errorf("解析响应失败: %w, 响应内容: %s", err, string(respBody))
	}

	// 检查响应码
	if resp.StatusCode != http.StatusOK {
		return result, fmt.Errorf("目标服务返回错误: HTTP %d", resp.StatusCode)
	}

	// 检查业务响应码
	if code, ok := result["code"].(float64); ok && code != 0 {
		msg := ""
		if m, ok := result["msg"].(string); ok {
			msg = m
		}
		return result, fmt.Errorf("目标服务业务错误: code=%v, msg=%s", code, msg)
	}

	return result, nil
}
