
// Code generated by hzx generator. you can insert router here.
package v1

import (
	"monitor_hub/internal/websocket"
	"github.com/cloudwego/hertz/pkg/app/server" 
)

func (s *TaskService) Register(h *server.Hertz, wsServer *websocket.Server) {
	root := h.Group("/",rootMw()...)
	_apis := root.Group("/apis",_apisMw()...)
	_v1 := _apis.Group("/v1",_v1Mw()...)
	_task := _v1.Group("/task",_taskMw()...)
	_task.POST("/create", append(_createtaskMw(), s.CreateTask)...)
	_task.POST("/get", append(_gettaskMw(), s.GetTask)...)
	_task.POST("/list", append(_listtaskMw(), s.ListTask)...)
	_task.POST("/update", append(_updatetaskMw(), s.UpdateTask)...)
	_task.POST("/del", append(_deletetaskMw(), s.DeleteTask)...)
	_task.POST("/icon/upload", append(_uploadiconMw(), s.UploadIcon)...)
	_task.POST("/forward", append(_forwardtaskMw(), s.ForwardTask)...)

	// websocket
	if wsServer != nil {
		// generate ws router code ... {topic}/{path} => s.handler.Ws{methodName}
	}
}
