// Code generated by hzx generator. DO NOT EDIT.
package v1

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	v1 "monitor_hub/apis/monitor_hub/task/v1"
	baseV1 "monitor_hub/apis/monitor_hub/base/v1"
)

type TaskService struct {
	handler *TaskHandler
}

func NewTaskService(handler *TaskHandler) *TaskService {
	return &TaskService{handler:handler}
}

// CreateTask
// @route /apis/v1/task/create [POST]
func (s *TaskService) CreateTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.CreateTaskRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.CreateTask(ctx, &req))
}

// GetTask
// @route /apis/v1/task/get [POST]
func (s *TaskService) GetTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req baseV1.IdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.GetTask(ctx, &req))
}

// ListTask
// @route /apis/v1/task/list [POST]
func (s *TaskService) ListTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req baseV1.QueryRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.ListTask(ctx, &req))
}

// UpdateTask
// @route /apis/v1/task/update [POST]
func (s *TaskService) UpdateTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.UpdateTaskRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.UpdateTask(ctx, &req))
}

// DeleteTask
// @route /apis/v1/task/del [POST]
func (s *TaskService) DeleteTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req baseV1.IdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.DeleteTask(ctx, &req))
}

// UploadIcon
// @route /apis/v1/task/icon/upload [POST]
func (s *TaskService) UploadIcon(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.UploadIconRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.UploadIcon(ctx, &req))
}

// ForwardTask
// @route /apis/v1/task/forward [POST]
func (s *TaskService) ForwardTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.ForwardTaskRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	if err := req.IsValid(); err != nil {
		baseV1.ResponseFailed(c, err, int64(baseV1.BaseErrorCode_INVALID_PARAM))
		return
	}
	c.JSON(consts.StatusOK, s.handler.ForwardTask(ctx, &req))
}


