// Code generated by hertz generator.

package hzcli

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/common/config"
	"github.com/cloudwego/hertz/pkg/protocol"
	v1 "exporter/pkg/datasource/apis/metrics/v1"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type Client interface {
	ReportMetrics(context context.Context, req *v1.ReportMetricsRequest, reqOpt ...config.RequestOption) (resp *v1.ReportMetricResponse, rawResponse *protocol.Response, err error)

	QueryMetrics(context context.Context, req *v1.MetricQuery, reqOpt ...config.RequestOption) (resp *v1.QueryMetricsResponse, rawResponse *protocol.Response, err error)

	GetStats(context context.Context, req *v1.GetStatsRequest, reqOpt ...config.RequestOption) (resp *v1.GetStatsResponse, rawResponse *protocol.Response, err error)
}

type MetricsServiceClient struct {
	client *cli
}

func NewMetricsServiceClient(hostUrl string, ops ...Option) (Client, error) {
	opts := getOptions(append(ops, withHostUrl(hostUrl))...)
	cli, err := newClient(opts)
	if err != nil {
		return nil, err
	}
	return &MetricsServiceClient{
		client: cli,
	}, nil
}

func (s *MetricsServiceClient) ReportMetrics(context context.Context, req *v1.ReportMetricsRequest, reqOpt ...config.RequestOption) (resp *v1.ReportMetricResponse, rawResponse *protocol.Response, err error) {
	httpResp := &v1.ReportMetricResponse{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{}).
		setPathParams(map[string]string{}).
		addHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("POST", "/apis/v1/metrics/batch")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

func (s *MetricsServiceClient) QueryMetrics(context context.Context, req *v1.MetricQuery, reqOpt ...config.RequestOption) (resp *v1.QueryMetricsResponse, rawResponse *protocol.Response, err error) {
	httpResp := &v1.QueryMetricsResponse{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{
			"app_id":      req.GetAppID(),
			"metric_name": req.GetMetricName(),
			"start_time":  req.GetStartTime(),
			"end_time":    req.GetEndTime(),
			"labels":      req.GetLabels(),
			"promql":      req.GetPromql(),
			"limit":       req.GetLimit(),
		}).
		setPathParams(map[string]string{}).
		addHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("GET", "/apis/v1/metrics/query")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

func (s *MetricsServiceClient) GetStats(context context.Context, req *v1.GetStatsRequest, reqOpt ...config.RequestOption) (resp *v1.GetStatsResponse, rawResponse *protocol.Response, err error) {
	httpResp := &v1.GetStatsResponse{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{
			"app_id": req.GetAppID(),
		}).
		setPathParams(map[string]string{}).
		addHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("GET", "/apis/v1/metrics/stats")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

var defaultClient, _ = NewMetricsServiceClient("localhost:8080")

func ConfigDefaultClient(ops ...Option) (err error) {
	defaultClient, err = NewMetricsServiceClient("localhost:8080", ops...)
	return
}

func ReportMetrics(context context.Context, req *v1.ReportMetricsRequest, reqOpt ...config.RequestOption) (resp *v1.ReportMetricResponse, rawResponse *protocol.Response, err error) {
	return defaultClient.ReportMetrics(context, req, reqOpt...)
}

func QueryMetrics(context context.Context, req *v1.MetricQuery, reqOpt ...config.RequestOption) (resp *v1.QueryMetricsResponse, rawResponse *protocol.Response, err error) {
	return defaultClient.QueryMetrics(context, req, reqOpt...)
}

func GetStats(context context.Context, req *v1.GetStatsRequest, reqOpt ...config.RequestOption) (resp *v1.GetStatsResponse, rawResponse *protocol.Response, err error) {
	return defaultClient.GetStats(context, req, reqOpt...)
}
