// Code generated by Validator v0.2.6. DO NOT EDIT.

package v1

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *QueryFilter) IsValid() error {
	return nil
}
func (p *QueryConfig) IsValid() error {
	return nil
}
func (p *RateStatistic) IsValid() error {
	return nil
}
func (p *CaseRateStatistics) IsValid() error {
	return nil
}
func (p *SingleCase) IsValid() error {
	if p.QueryConfig != nil {
		if err := p.QueryConfig.IsValid(); err != nil {
			return fmt.Errorf("field QueryConfig not valid, %w", err)
		}
	}
	if p.RateStatistics != nil {
		if err := p.RateStatistics.IsValid(); err != nil {
			return fmt.Errorf("field RateStatistics not valid, %w", err)
		}
	}
	return nil
}
func (p *Chunk) IsValid() error {
	return nil
}
func (p *MetricInfo) IsValid() error {
	return nil
}
func (p *Report) IsValid() error {
	if p.ReportStatus != nil {
		if err := p.ReportStatus.IsValid(); err != nil {
			return fmt.Errorf("field ReportStatus not valid, %w", err)
		}
	}
	if p.ScoringConfig != nil {
		if err := p.ScoringConfig.IsValid(); err != nil {
			return fmt.Errorf("field ScoringConfig not valid, %w", err)
		}
	}
	if p.ReportScore != nil {
		if err := p.ReportScore.IsValid(); err != nil {
			return fmt.Errorf("field ReportScore not valid, %w", err)
		}
	}
	if p.MetricInfo != nil {
		if err := p.MetricInfo.IsValid(); err != nil {
			return fmt.Errorf("field MetricInfo not valid, %w", err)
		}
	}
	return nil
}
func (p *ReportStatus) IsValid() error {
	return nil
}
func (p *ScoringRange) IsValid() error {
	return nil
}
func (p *ThresholdCondition) IsValid() error {
	return nil
}
func (p *MetricScoringConfig) IsValid() error {
	return nil
}
func (p *CaseScoringConfig) IsValid() error {
	return nil
}
func (p *ReportScoringConfig) IsValid() error {
	if p.DefaultConfig != nil {
		if err := p.DefaultConfig.IsValid(); err != nil {
			return fmt.Errorf("field DefaultConfig not valid, %w", err)
		}
	}
	return nil
}
func (p *MetricScore) IsValid() error {
	return nil
}
func (p *CaseScore) IsValid() error {
	return nil
}
func (p *ReportScore) IsValid() error {
	return nil
}
func (p *UpdateReportRequest) IsValid() error {
	if len(p.ID) < int(1) {
		return fmt.Errorf("field ID min_len rule failed, current value: %d", len(p.ID))
	}
	if p.Report == nil {
		return fmt.Errorf("field Report not_nil rule failed")
	}
	if err := p.Report.IsValid(); err != nil {
		return fmt.Errorf("field Report not valid, %w", err)
	}
	return nil
}
func (p *UploadIconRequest) IsValid() error {
	if len(p.ReportID) < int(1) {
		return fmt.Errorf("field ReportID min_len rule failed, current value: %d", len(p.ReportID))
	}
	if len(p.IconData) < int(1) {
		return fmt.Errorf("field IconData min_len rule failed, current value: %d", len(p.IconData))
	}
	if len(p.FileName) < int(1) {
		return fmt.Errorf("field FileName min_len rule failed, current value: %d", len(p.FileName))
	}
	if len(p.FileName) > int(100) {
		return fmt.Errorf("field FileName max_len rule failed, current value: %d", len(p.FileName))
	}
	return nil
}
func (p *ForwardReportRequest) IsValid() error {
	if len(p.TargetURL) < int(1) {
		return fmt.Errorf("field TargetURL min_len rule failed, current value: %d", len(p.TargetURL))
	}
	if len(p.ReportID) < int(1) {
		return fmt.Errorf("field ReportID min_len rule failed, current value: %d", len(p.ReportID))
	}
	return nil
}
func (p *ImportReportRequest) IsValid() error {
	if len(p.SourceID) < int(1) {
		return fmt.Errorf("field SourceID min_len rule failed, current value: %d", len(p.SourceID))
	}
	if p.Report == nil {
		return fmt.Errorf("field Report not_nil rule failed")
	}
	if err := p.Report.IsValid(); err != nil {
		return fmt.Errorf("field Report not valid, %w", err)
	}
	return nil
}
