// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	v1_2 "monitor_hub/biz/datasource/v1"
	v1_3 "monitor_hub/biz/filetree/v1"
	v1_4 "monitor_hub/biz/points/v1"
	v1_5 "monitor_hub/biz/report/v1"
	v1_6 "monitor_hub/biz/task/v1"
	"monitor_hub/config/v1"
	"monitor_hub/internal/hzapp"
	"monitor_hub/internal/provider"
	"monitor_hub/internal/trigger"
	"monitor_hub/internal/websocket"
	"monitor_hub/pkg/aggregator"
	"monitor_hub/pkg/mongodb"
	"monitor_hub/pkg/repo"
	trigger2 "monitor_hub/pkg/trigger"
	"sync"
)

// Injectors from wire.go:

func New(configFilePath2 string) (*Monitor_hubApp, error) {
	appContext := ProvideAppContext()
	config := v1.New(configFilePath2)
	waitGroup := ProvideWaitGroup()
	context := ProvideContext(appContext)
	triggerManager := trigger.NewTriggerManager(context)
	manager := websocket.NewManager(context, config, triggerManager)
	mongoDB := mongodb.New(config)
	datasourceRepo := repo.NewDatasourceRepo(mongoDB)
	reportRepo := repo.NewReportRepo(mongoDB)
	taskRepo := repo.NewTaskRepo(mongoDB)
	generatedDeps := provider.ProvideGeneratedDeps(config, mongoDB, datasourceRepo, reportRepo, taskRepo)
	datasourceStatusChecker := trigger2.NewDatasourceStatusChecker(datasourceRepo)
	datasourceStatusTrigger := trigger2.NewDatasourceStatusTrigger(config, datasourceStatusChecker)
	aggregatorConfig := provider.ProvideAggregatorConfig(config)
	serializer := aggregator.NewAggregatedPointSerializer()
	storage, err := provider.ProvideAggregatedPointStorage(config, serializer, triggerManager)
	if err != nil {
		return nil, err
	}
	collector := provider.ProvideCollector(datasourceRepo)
	aggregatorManager, err := provider.ProvideAggregatorManager(aggregatorConfig, storage, collector, manager)
	if err != nil {
		return nil, err
	}
	aggregationTrigger := aggregator.NewAggregationTrigger(aggregatorManager)
	cleanupTrigger := aggregator.NewCleanupTrigger(aggregatorManager)
	triggerDeps := provider.ProvideTriggerDeps(datasourceStatusTrigger, aggregationTrigger, cleanupTrigger)
	server := ProvideWSServer(manager)
	datasourceBroadcaster := v1_2.NewDatasourceBroadcaster(config, datasourceRepo, datasourceStatusChecker)
	datasourceHandler := v1_2.NewDatasourceHandler(config, datasourceRepo, server, datasourceBroadcaster)
	datasourceService := v1_2.NewDatasourceService(datasourceHandler)
	filetreeHandler := v1_3.NewFiletreeHandler(config, server)
	filetreeService := v1_3.NewFiletreeService(filetreeHandler)
	pointsHandler := v1_4.NewPointsHandler(config, server, storage, datasourceRepo)
	pointsService := v1_4.NewPointsService(pointsHandler)
	pointsBroadcaster := v1_4.NewPointsBroadcaster(config)
	reportHandler := v1_5.NewReportHandler(config, server, datasourceRepo, reportRepo, collector)
	reportService := v1_5.NewReportService(reportHandler)
	taskHandler := v1_6.NewTaskHandler(config, server, taskRepo)
	taskService := v1_6.NewTaskService(taskHandler)
	bizDeps := provider.ProvideBizDeps(datasourceHandler, datasourceService, datasourceBroadcaster, filetreeHandler, filetreeService, pointsHandler, pointsService, pointsBroadcaster, reportHandler, reportService, taskHandler, taskService)
	customDeps := provider.ProvideCustomDeps(datasourceStatusChecker, aggregatorConfig, collector, serializer, storage, aggregatorManager)
	hertzApp := hzapp.NewHertzApp(config, manager, triggerManager, generatedDeps, triggerDeps, bizDeps, customDeps)
	monitor_hubApp := newMonitor_hubApp(appContext, config, waitGroup, hertzApp)
	return monitor_hubApp, nil
}

// wire.go:

// ProvideAppContext 提供应用的可取消 Context
// AppContext 定义在 app.go 中
func ProvideAppContext() *AppContext {
	ctx, cancel := context.WithCancel(context.Background())
	return &AppContext{
		Context: ctx,
		Cancel:  cancel,
	}
}

// ProvideContext 从 AppContext 中提取 Context 供触发器使用
func ProvideContext(appCtx *AppContext) context.Context {
	return appCtx.Context
}

// ProvideWaitGroup 提供 WaitGroup 用于等待所有触发器的 goroutine
func ProvideWaitGroup() *sync.WaitGroup {
	return &sync.WaitGroup{}
}

// ProvideWSServer 提供 WebSocket Server
func ProvideWSServer(wsManager *websocket.Manager) *websocket.Server {
	return wsManager.GetWSServer()
}
