// Code generated by hzx generator. DO NOT EDIT.
package v1

import (
	"log"
	"git.woa.com/castlexu/goutils/tools"
)

type HealthCheck struct {
    Timeout string `json:"timeout" yaml:"timeout"`
    Interval string `json:"interval" yaml:"interval"`
    DeregisterCriticalServiceAfter string `json:"deregister_critical_service_after" yaml:"deregister_critical_service_after"`
}

type Consul struct {
    ServiceName string `json:"service_name" yaml:"service_name"`
    Weight int `json:"weight" yaml:"weight"`
    HealthCheck HealthCheck `json:"health_check" yaml:"health_check"`
    Enable bool `json:"enable" yaml:"enable"`
    Address string `json:"address" yaml:"address"`
}

type Websocket struct {
    RegisterChannelSize int `json:"register_channel_size" yaml:"register_channel_size"`
    BroadcastChannelSize int `json:"broadcast_channel_size" yaml:"broadcast_channel_size"`
    WriteWait int `json:"write_wait" yaml:"write_wait"`
    PongWait int `json:"pong_wait" yaml:"pong_wait"`
    MaxMessageSize int `json:"max_message_size" yaml:"max_message_size"`
    SendChannelSize int `json:"send_channel_size" yaml:"send_channel_size"`
    UnregisterChannelSize int `json:"unregister_channel_size" yaml:"unregister_channel_size"`
    Enable bool `json:"enable" yaml:"enable"`
    PingPeriod int `json:"ping_period" yaml:"ping_period"`
    ReadBufferSize int `json:"read_buffer_size" yaml:"read_buffer_size"`
    WriteBufferSize int `json:"write_buffer_size" yaml:"write_buffer_size"`
}

type Storage struct {
    Type string `json:"type" yaml:"type"`
    DataDir string `json:"data_dir" yaml:"data_dir"`
    MaxBlockDuration string `json:"max_block_duration" yaml:"max_block_duration"`
    RetentionDays int `json:"retention_days" yaml:"retention_days"`
    CompactionInterval string `json:"compaction_interval" yaml:"compaction_interval"`
    MaxChunkSize int `json:"max_chunk_size" yaml:"max_chunk_size"`
    WriteBufferSize int `json:"write_buffer_size" yaml:"write_buffer_size"`
    MixBlockDuration string `json:"mix_block_duration" yaml:"mix_block_duration"`
    MemoryCleanupInterval string `json:"memory_cleanup_interval" yaml:"memory_cleanup_interval"`
}

type Mark struct {
    AggregateInterval string `json:"aggregate_interval" yaml:"aggregate_interval"`
    Ttl string `json:"ttl" yaml:"ttl"`
    ChannelSize int `json:"channel_size" yaml:"channel_size"`
    CleanupInterval string `json:"cleanup_interval" yaml:"cleanup_interval"`
}

type HertzServer struct {
    KeepAliveTimeout int `json:"keep_alive_timeout" yaml:"keep_alive_timeout"`
    IdleTimeout int `json:"idle_timeout" yaml:"idle_timeout"`
    ReadTimeout int `json:"read_timeout" yaml:"read_timeout"`
    MaxRequestBodySize int `json:"max_request_body_size" yaml:"max_request_body_size"`
    MaxKeepBodySize int `json:"max_keep_body_size" yaml:"max_keep_body_size"`
    KeepAlive bool `json:"keep_alive" yaml:"keep_alive"`
    HttpPort int `json:"http_port" yaml:"http_port"`
    PprofPort int `json:"pprof_port" yaml:"pprof_port"`
    StreamBody bool `json:"stream_body" yaml:"stream_body"`
    ExitWaitTime int `json:"exit_wait_time" yaml:"exit_wait_time"`
    ReadBufferSize int `json:"read_buffer_size" yaml:"read_buffer_size"`
}

type IndexeItem struct {
    Collection string `json:"collection" yaml:"collection"`
    Keys []string `json:"keys" yaml:"keys"`
}

type Mongodb struct {
    Enable bool `json:"enable" yaml:"enable"`
    Uri string `json:"uri" yaml:"uri"`
    WMajority bool `json:"w_majority" yaml:"w_majority"`
    PoolSize int `json:"pool_size" yaml:"pool_size"`
    Dbname string `json:"dbname" yaml:"dbname"`
    Indexes []IndexeItem `json:"indexes" yaml:"indexes"`
}

type Config struct {
    Consul Consul `json:"consul" yaml:"consul"`
    Websocket Websocket `json:"websocket" yaml:"websocket"`
    Storage Storage `json:"storage" yaml:"storage"`
    Mark Mark `json:"mark" yaml:"mark"`
    HertzServer HertzServer `json:"hertz_server" yaml:"hertz_server"`
    Mongodb Mongodb `json:"mongodb" yaml:"mongodb"`
}

func New(filePath string) *Config {
    cfg := &Config{}
    err := tools.LoadYaml(filePath, cfg)
    if err != nil {
        log.Fatalf("load %v config err , %v", filePath, err)
    }
    return cfg
}