// Code generated by hzx generator.

package main

import (
	"monitor_hub/cmd/monitor_hub/app"
	"os"

	"git.woa.com/castlexu/goutils/cli"
)

func main() {
	cmd := app.NewServerCommand()
	code := cli.Run(cmd)
	os.Exit(code)
}
